### ISSUE TITLE
Add a version check in CMake to verify that icub-main is linking against correct version of icub-firmware-shared 

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-main#107]
@drdanz ?

**Comment by drdanz** [comment]
icub-firmware-shared already has a version number that is checked in icub-main, it is just a question of changing it...

**Comment by lornat75** [comment]
Ok, we should just make sure it is maintained up to date: @randaz81 @marcoaccame @barbalberto

**Comment by lornat75** [comment]
For completeness:

Version check in icub-main is done here: https://github.com/robotology/icub-main/blob/master/conf/iCubFindDependencies.cmake#L31
Version check of icub-firmware-shared is set here: https://github.com/robotology/icub-firmware-shared/blob/master/CMakeLists.txt#L11

**Comment by randaz81** [comment]
It works, but the error message that I get is: "cannot find icub_firmware_shared library, turn off device ecc"" which can be somehow confusing and does not print the required vs found version (like in yarp)

**Comment by lornat75** [comment]
@drdanz

**Comment by drdanz** [comment]
This is coherent with what the icub-main repository does for the other dependencies, what kind of behaviour do you want? And do you want to change it for all the dependencies?

**Comment by barbalberto** [comment]
the point was simply to change the error message to be like:

found icub_firmware_version is too old, found version xxx, required version yyy 

like we do on yarp instead of telling not found (which is not entirely true, it is found but wrong version)
