### ISSUE TITLE
Matlab Function to get the Regressor Matrix ''Y( . )''

### ISSUE THREAD

**Issue by DiegoRomeres** [robotology/icub-main#112]
Considering the model 

f = Y( v , a ) \times \alpha

where:
'f' is the spatial net force acting on a rigid body
'v,a' are the spatial velocity and acceleration of the body, respectively
'Y( . , . )' the regressor matrix
'\alpha' the body's interial parameters,

is it possible to have a Matlab function which given 'v,a' returns 'Y( . , .)' ?

thanks

**Comment by iron76** [comment]
@DiegoRomeres: currently @ommac is trying the C++ interface. I think that after the IROS deadline we could have a look at how much work is needed to create a simple Matlab interface. Two persons have done this in the past: @jeljaik and @naveenoid.

**Comment by traversaro** [comment]
Initial implementation of matlab bindings for iDynTree was merged in https://github.com/robotology-playground/idyntree/pull/28 . Regressor generation is still not covered, but I thinks we can discuss about this in the iDynTree issues.

**Comment by traversaro** [comment]
Just to "actually" close the issue. The first example for computation of regressor matrices using Matlab is available in https://github.com/robotology-playground/idyntree/tree/master/examples/matlab/iCubLeftArmDynamicRegressors .
