### ISSUE TITLE
Broken link: http://wiki.icub.org/iCub/main/dox/html/group__dataSetPlayerExample.html

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-main#117]
This page http://wiki.icub.org/wiki/Check_your_installation contains broken link to http://wiki.icub.org/iCub/main/dox/html/group__dataSetPlayerExample.html

The page pointed by this link was generated by doygen form .dox file in:

app\dataSetPlayer

which got moved with the dataSetPLayer gui to YARP. However the documentation is not generated in YARP. @drdanz

**Comment by drdanz** [comment]
The new address of the example is

  http://wiki.icub.org/yarpdoc/group__yarpdataplayerExample.html

The app is now in ``<yarp>/src/yarpdataplayer``

**Comment by lornat75** [comment]
ok thanks, updated.
