### ISSUE TITLE
Gaze control problem in position-direct mode

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#129]
We've been spotting problems with `iKinGazeCtrl` set in `position-direct` mode.

/cc @randaz81 @vtikha @alecive @lornat75 

##### Instructions to disable `position-direct` mode
To temporarily disable the `position-direct` mode and kind of downgrade the performance going back to `velocity` mode, do as follows:

1. Identify the `iKinGazeCtrl` configuration file: `yarp resource --context iKinGazeCtrl --find config.ini` (if the gaze controller is not launched pointing to a different file).
2. If the identified file is not in `.local` (or in `%APPDATA%` under Windows), install it: `yarp-config context --import iKinGazeCtrl config.ini`.
3. Edit the installed file by adding the option: `neck_position_control off`.

##### Checking if `velocity` mode is enabled
1. Run: `iKinGazeCtrl`.
2. Check among `[INFO]` if there is the message: `### neck control - requested VELOCITY mode => VELOCITY mode selected`.

**Comment by lornat75** [comment]
I believe we should first write and run a test for position-direct, then proceed with debugging the specific problems with iKinGazeCtrl. What do you think?

**Comment by pattacini** [comment]
It's fine with me; I can help debugging either way.
The weird thing is that:
- `cartesiancontrollerserver` is still working in `position-direct`;
- `iKinGazeCtrl` has not changed since months and it was fully functional in `position-direct` until let's say two weeks ago;
- this problem emerged first on ethernet robots while Blacky was ok with the same SW release, then _infected_ the Blacky;

**Comment by lornat75** [comment]
Strange... Maybe running a generic test for position-direct on the arms and the head can reveal something...

**Comment by alecive** [comment]
@pattacini it might be that the problems on the blackie are different from the problems on the ETH robots (with similar outcomes) :)

**Comment by pattacini** [comment]
Uhm... it might certainly be but, actually, I've seen exactly the same behavior both on `iCubLisboa01` and `Blacky`/`Bluey`: they are different in terms of ETH/CAN and FW std/exp.

**Comment by pattacini** [comment]
I've added up some messages to `iKinGazeCtrl` to investigate the issue. Suddenly, on `Blacky` the `position-direct` started over working fine. We have to repeat the experiment on `Reddy` or `Bluey`: stay tuned.

At the same time, @randaz81 performed single-joint test on the neck in `position-direct` mode; found nothing special: it worked. Next experiment will involve the control of multiple joints.

**Comment by pattacini** [comment]
Update on this.

I managed to run some tests on the gaze controller and I found it is behaving correctly.

The figure below shows, for each joint of the neck, the `position-direct` commands in blue, the `feedback` in red and the `gate` in orange, the latter accounting for the time periods when the controller is active.
![fig-0](https://cloud.githubusercontent.com/assets/3738070/6980923/c9e1bd82-d9f9-11e4-94bc-53b43d33afb1.png)

Circled in red the weird event happening on the yaw joint is zoomed in below:
![fig-1](https://cloud.githubusercontent.com/assets/3738070/6980957/63628ffe-d9fa-11e4-86e0-7a426d393c27.png)

As you can see, there is an unwanted snap stop while the joint is moving. The controller is however producing a smooth varying reference.

Attached the [archive](https://files.zenhub.io/551e67b6a5fa455769d2d176) containing the logged data along with the MATLAB script used to generate the graphs.

Further investigations are thus required to see whether those commands are actually received at the PC104 side.

/cc @randaz81 @lornat75

**Comment by lornat75** [comment]
Friction?

**Comment by pattacini** [comment]
I've already thought friction might play its role, but how likely can it be happening all of a sudden and on many different robots?

**Comment by pattacini** [comment]
I tend to exclude `stiction` because the snap stop is at the middle of trajectory.
It would be interesting to understand whether we have this snap stop always in correspondence of roughly the same yaw angle.

**Comment by pattacini** [comment]
**I got it!**

With the aim of narrowing down the problem, I've designed this [**`test program`**](https://files.zenhub.io/55858c7fa5e87d7a13418be2) that basically takes as input the data logged from the port `iKinGazeCtrl/dbg:o` and then sends the same commands to the robot. This way I managed to fully decouple from the gaze controller.

###### Preamble
The gaze controller opens up the device driver making use of the **`writeStrict`** option (see [here](https://github.com/robotology/icub-main/blob/master/src%2Fmodules%2FiKinGazeCtrl%2Fsrc%2Fmain.cpp#L1034)), because it has to send both direct positions (to the neck) and velocities (to the eyes) at each control slot of `10 ms`, therefore we don't want to lose data.

###### Then, we have two cases
1. If I keep sending `poss`+`vels` each slot, I can see the problem appearing along with the test program.
2. If I send just the `poss` and skip `vels` (i.e. launch: `txTarget --vel off` that corresponds to commenting out [this line](https://github.com/robotology/icub-main/blob/master/src%2Fmodules%2FiKinGazeCtrl%2Fsrc%2Fcontroller.cpp#L646)), the movements remain smooth!

###### To sum up
The `writeStrict` was used to function in the past, and in fact `iKinGazeCtrl` was running fine in `position-direct` mode; what happened?
Can we look into it asap, please?

/cc @lornat75 @barbalberto @randaz81 @alecive @vtikha

**Comment by alecive** [comment]
Great! This seem to fit also with some issues I had with the gazeStabilizer during its early stages of development. I don't remember exactly the context, but it was related to the fact that I was sending commands at the neck decoupled from those at the eyes.

**Comment by traversaro** [comment]
Greate indeed! I am curious to check if is a problem of the `writeStrict` option (i.e. the streaming messages are not sent from the `RemoteControlBoard`) or a problem of the `Contro;BoardWrapper` callback (i.e. the messages too close are not properly received).

**Comment by pattacini** [comment]
Once this issue will be solved, I hope to see regression tests running overnight to prevent the same bother from happening again :smirk: 

[Some developers](https://github.com/robotology/icub-tests#contributers) worked hard to design and implement those [tests](https://github.com/robotology/icub-tests), it's then a pity they are not used yet.

**Comment by lornat75** [comment]
I think the problem could be the callback of the buffered port discarding messages that are too close. Can you try calling setStrict():

http://eris.liralab.it/yarpdoc/classyarp_1_1os_1_1BufferedPort.html#a66c1b8b92b88fbb1a9bc329819788806

In this case delay may accumulate if the ControlBoardWrapper cannot read messages quickly enough but let's see what happens.

**Comment by pattacini** [comment]
Thanks to @barbalberto this issue seems to be finally solved!

**Comment by pattacini** [comment]
@robotology/qa-users 
you are warmly suggested to restore **`position-direct`** mode of `iKinGazeCtrl` as per instructions outlined [here](https://github.com/robotology/icub-main/issues/129#issue-64464506).

Remember to update `yarp`.
