### ISSUE TITLE
Stiction up/down params for position control on ETH firmware

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#132]
As agreed with @randaz81 we should check whether the stiction `up` and `down` parameters used in position control mode have been correctly ported to be used along with ETH firmware.

These parameters are relevant for [`fingersTuner`](http://wiki.icub.org/iCub/main/dox/html/group__icub__fingersTuner.html) tool.

**Comment by randaz81** [comment]
looking in robotology\firmware\*, searching for:
`ICUBCANPROTO_POL_MC_CMD__SET_POS_STICTION_PARAMS`
`ICUBCANPROTO_POL_MC_CMD__GET_POS_STICTION_PARAMS`
`ICUBCANPROTO_POL_MC_CMD__SET_TORQUE_STICTION_PARAMS`
`ICUBCANPROTO_POL_MC_CMD__GET_TORQUE_STICTION_PARAMS`
and double checking with the contents of the file:
`robotology\icub-firmware\emBODY\eBcode\arch-arm\board\ems004\appl\v2\cfg\eoprot-callbacks`
I can state that those parameters are not transmitted to MC4 boards on the ETH architecture. They have to be implemented.

**Comment by valegagge** [comment]
@randaz81 Is it still necessary to implement these messages?

**Comment by pattacini** [comment]
@valegagge yes :smile:

**Comment by pattacini** [comment]
@valegagge any rough estimate on when we could have this implemented?

**Comment by valegagge** [comment]
I hope to close this issue before of  23 September.

**Comment by valegagge** [comment]
Now ems firmware sends and reads stiction params from/to mc4 (CAN).

(See icub-firmware@ce2a729d92321cfb5e4e744b759e953b79c4a12a)

I tested firmware on purple iCub by setting and raeding stinction params by yarprobotgui. It seems work fine.

**Comment by pattacini** [comment]
Thanks @valegagge 🌹 
Sooner or later, I'll have the chance to test the `fingersTuner` module over this update.
