### ISSUE TITLE
iCubGui does not close ports

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#137]
`iCubGui` does not close ports when shutting down (at least on my windows).

/cc @alecive @lornat75 @aitek4iit

**Comment by aitek4iit** [comment]
It should have been fixed now. Please let me know if the fix works.

**Comment by pattacini** [comment]
It works, thanks!

Next time, could you please do `git pull --rebase` just before publishing your local commits with `git push`? This way we can avoid creating unnecessary branching in git history.

**Comment by aitek4iit** [comment]
Ok!
