### ISSUE TITLE
ActionsRenderingEngine should support block_eyes for all actions

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-main#139]
Hi all,

as agreed with Ugo, it would be useful to have the block_eyes option for all actions, rather than only for ```look```. In our scenario, we need it to keep the eye configuration which was used to calibrate the iCub eyes in SFM (stereo-vision).

The changes needed shouldn't be too bad.

Thanks a lot and best wishes,
Tobias

**Comment by pattacini** [comment]
it should suffice to do the following:
`actionsRenderingEngine --motor::block_eyes 5.0`
