### ISSUE TITLE
iCubSkinGui does not close ports on closure

### ISSUE THREAD

**Issue by alecive** [robotology/icub-main#141]
We have experienced this issue on `iCubGenova01` during the Shanghai demo. The sw was not updated, but I suspect the issue to be there also on the up-to-date software. I'll check it on my way back in Genova.

 cc @pattacini @randaz81 @ale-git @super-ste @julijenv

**Comment by pattacini** [comment]
@alecive could you test it tomorrow?
Blackie is available now
