### ISSUE TITLE
Errors when starting robotInterface in log

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-main#143]
Hi all,
we just recently updated yarp, icub-main and icub-firmware-shared on pc104 and our main machine. As we also started using yarplogger, we noticed several errors when launching robotInterface.

The error is as follows: 
```
233		6.002969		ERROR		TORQUE_PIDS: 'controlUnits' param missing. Assuming machine_units. Please fix your configuration file.
```

The same error is repeated for in total 12 times. Going through the recent commits, we noticed that this has something to do with the ETH robots (e.g. https://github.com/robotology/icub-main/commit/1a38740c51c76633b4098a47419de951629c1878). However, we have an CAN-BUS based robot.

The robot however starts nicely, and we don't have any issues running any other modules.

Would be great if this could be fixed :+1: 

Please let me know if you need the complete logfile.

Thanks a lot,
Tobias

**Comment by lornat75** [comment]
This looks more like something that should be handled by "support".
