### ISSUE TITLE
torso.ini iCubSkinGui inconsistency 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#156]
Apparently in https://github.com/robotology/icub-main/blob/master/app/skinGui/conf/skinGui/torso.ini#L104 there are two triangles with Number 52 that share the same position, but one is of the legacy type `triangle`. I guess that this is just a typo and the last one can be removed?

@ale-git @alecive @maggia80 @matejhof

**Comment by maggia80** [comment]
Yes you can remove it. It is a mistake

**Comment by traversaro** [comment]
:+1:
