### ISSUE TITLE
Move pf3d* modules into icub-basic-demos repository

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#192]
`pf3dBottomup` and `pf3dTracker` modules can be conveniently moved into [**`icub-basic-demos`**](https://github.com/robotology/icub-basic-demos) repository.

/cc @gsaponaro @alecive

**Comment by gsaponaro** [comment]
OK, cool.
I can also clean up and update a bit the code (i.e., use RFModule and latest yInfo macros).
What does IFI mean?

**Comment by pattacini** [comment]
@gsaponaro great, you're willing to help clean those modules, you're more than welcome. Go ahead with a **PR** then, and I'll take care of moving them to their final destination.

To find out more on the **IFI Day** events, visit [![iCub Research](http://ssl.gstatic.com/images/icons/gplus-32.png)](https://plus.google.com/u/0/communities/116897884020660435466/stream/ad8c0921-e748-480a-98c3-9f479c3f76e4) and if you like it you can ask to join us :smile:

**Comment by alecive** [comment]
:+1:

**Comment by gsaponaro** [comment]
Hi @pattacini, regarding **pf3dBottomup** which you just upgraded (cool), I just wanted to mention that there are issues with that module stability, for me it crashes upon ctrl+c, seemingly due to a memory leak in function ```calc_hist_model_2D()```. I'm not sure whether this hinders moving the module to another repo, probably not. We can fix it in the new location too.

**Comment by pattacini** [comment]
We don't use `pf3dBottomup` module so I can't help.
However it can be fixed conveniently in the new location, as you said.

**Comment by pattacini** [comment]
https://github.com/robotology/icub-main/commit/6aace36329f884c2b8fe0c41259fa9665eeb7f89 moves **`pf3d*`** modules into [**`icub-basic-demos`**](https://github.com/robotology/icub-basic-demos) with https://github.com/robotology/icub-basic-demos/commit/7cc8bebccd5310e1958a143366afea13298653bc
