### ISSUE TITLE
Improve switching to torque control mode

### ISSUE THREAD

**Issue by francesco-romano** [robotology/icub-main#196]
There are currently two issues when switching a control board into torque mode:

1. **initial references**.
It seems that at the current state a reference of zero torque is set. While this is ok with position and velocity control, the choice of an initial reference for a torque control is more subtle. A proposal is to keep as a reference the same torque read at the moment of switching.
2. **delay in the change of control mode**.
We are experiencing a big (and visible) delay while we switch control mode. The nature of this delay is still to be determined. 
The code responsible of the switch at high level (balancing) is the following: https://github.com/robotology-playground/yarp-wholebodyinterface/blob/master/src/yarpWholeBodyActuators.cpp#L372-L426

cc: @randaz81 @DanielePucci @traversaro

**Comment by traversaro** [comment]
We should use the multijoint version of setControlMode and setRefTorque to see if this delay is reduced.

**Comment by alecive** [comment]
+1 @traversaro

**Comment by pattacini** [comment]
@francesco-romano any update happened to these two points in the meantime?

**Comment by francesco-romano** [comment]
The first issue has been solved by @ale-git  almost one year ago.
For the second one, we need to test again everything, so I think it is safe to close this issue for now, and reopen it if needed.
