### ISSUE TITLE
Windows installer when iCub-main is not selected adds cmake files in robotology/icub-1.1.16

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-main#198]
@mbrunettini

**Comment by pattacini** [comment]
@mbrunettini please take note of this while producing new binaries in the upcoming days.

**Comment by mbrunettini** [comment]
It think I've already fixed.
I will test it anyway, of course

**Comment by mbrunettini** [comment]
Issue fixed in icub-1.1.17
