### ISSUE TITLE
controlMode devices should check concistency of rotor index params in xml file

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-main#226]
in mechanicals files,  there are two params: "HasRotorEncoderIndex" and "RotorIndexOffset". 

motionCointrol Devices (such as EmbObjMotioncontrol) should perform following check:

if "HasRotorEncoderIndex"  is zero, then "RotorIndexOffset" must be zero, else signal error and terminate robotInterface

**Comment by pattacini** [comment]
Hi @valegagge 

Is this check implemented by now?

**Comment by valegagge** [comment]
fixed with 6b0d71094c74c06b65b989669556ced9dac5ada3.

Tested on icubGenova04. All is ok.
