### ISSUE TITLE
wrong axis names

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-main#229]
Check the axis names stored in the legs and the torso xml files.
On some robots, some axis names are swapped.

**Comment by randaz81** [comment]
A critical issue has been fixed by commits:
73a2321
b976033
the axisName variable was not properly handled by the axisMap helper. However, this suggests that other xml parameters could be affected by the same bug (e.g. the parameter of one joint could be set on a different joint). It's thus necessary an investigation all parameters.

**Comment by traversaro** [comment]
cc @nunoguedelha
