### ISSUE TITLE
Command 'iCub_SIM' giving error

### ISSUE THREAD

**Issue by muhammadalidildar** [robotology/icub-main#233]
Dear all, I want to test iCub and trying command 'iCub_SIM' in a terminal window. It gives the following error:
"iCub_SIM: symbol lookup error: iCub_SIM: undefined symbol: _ZTIN4yarp3dev22ImplementMotorEncodersE"

Whereas YARP is running fine. Please help me a little to figure out the problem.
Thank you very much in advance.

**Comment by pattacini** [comment]
No one has still tackle this issue to help @muhammadalidildar.
This is a good test for young people to help the community.

@massimoregoli @GiuliaP @tanismar @jeljaik @Ommac @bhigy please take this up.

**Comment by jeljaik** [comment]
@muhammadalidildar assuming you're on Linux can you post the output of `ldd iCub_SIM` to see against which shared libraries it's trying to link?

**Comment by muhammadalidildar** [comment]
Yes I am running it on Ubuntu. "ldd iCub_SIM" is giving the following error:
ldd: ./iCub_SIM: No such file or directory

**Comment by Tobias-Fischer** [comment]
Try `ldd "$(which iCub_SIM)"`

**Comment by jeljaik** [comment]
Yes sorry, forgot to say you have to do that in the directory where iCub_SIM has been installed, so, either in:
`$ICUB_DIR/bin`
or wherever you installed icub-main

**Comment by muhammadalidildar** [comment]
I am very much thankful to all of you. I guess I did something wrong while installing. I installed YARP from sources and iCub from binaries. So I uninstalled and reinstalled both from binaries. Now they are working fine.

**Comment by pattacini** [comment]
@muhammadalidildar glad to know that you found a solution, even though in principle there shouldn't be any problem with the setting `yarp(sources)` + `icub(binaries)`.

thanks @jeljaik for your commitment! :+1:
