### ISSUE TITLE
Skin ports remain up after closing robotInterface

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-main#235]
I am currently working on Purpley (`iCubGenova02`), and after closing `robotInterface` some ports related to the skin stay up.

Feel free to close this issue if it is a duplicate of some other issue.

![screenshot from 2015-11-04 10 13 23](https://cloud.githubusercontent.com/assets/5045846/10934085/bb977b3a-82dd-11e5-9863-5e3a35632973.png)

@marcoaccame @pattacini @drdanz @francesco-romano

**Comment by DanielePucci** [comment]
@barbalberto

**Comment by pattacini** [comment]
Another issue which seems suitable for young researchers. It would be helpful to exercise their debugging abilities and also for them to get more feeling with the gut of our system.

@tanismar @massimoregoli @GiuliaP @bhigy @giuliavezzani @jeljaik and whoever wants to be remembered as the quest's winner.

**Comment by pattacini** [comment]
@bhigy would you be willing to take up this task?

**Comment by bhigy** [comment]
I'll try to have a look when I find a moment.

**Comment by pattacini** [comment]
Great, thanks.

**Comment by lornat75** [comment]
The first thing I would check is if ports are created dynamically or statically. If they are created dynamically (i.e. using new) check that close (and destructors) call delete.

**Comment by giuliavezzani** [comment]
If @bhigy is too busy in this period, I can try to fix the problem the next
month,  as soon as all the bureaucratic tasks will be finished :)

2015-11-22 11:04 GMT+01:00 Lorenzo Natale <notifications@github.com>:

**Comment by barbalberto** [comment]
If I remember correctly, the skin wrapper create dinamically a set of analogServers using ``new``.
Maybe something is not right in the cleanup.
Both classes are located in the icub-main/icubmod, if someone wants to address this issue I can help giving a couple of hints for a quick start.
