### ISSUE TITLE
iKinGazeCtrl with saccades not moving the neck; program hangs

### ISSUE THREAD

**Issue by lorejam** [robotology/icub-main#238]
We are having an issue with iCubLisboa01. We updated all the software this week: yarp, Ipopt 3.12.4, icub-firmware-shared, icub-main.

When we try to fixate a 3D point using iKinGazeCtrl (i.e., sending a 3D vector through the xd:i port) with the saccades option on, the robot just moves the eyes (it performs the saccadic movement) but not the neck, and then iKinGazeCtrl (running in a terminal with --verbose on) prints the IpOpt banner and hangs (it does not print the verbose debug messages about joints positions/velocities any more).
After this, any other message that we send to xd:i is ignored (i.e., not received or processed).

We reproduced the problem both with and without position-direct (neck_position_control on/off).

Note: if we repeat the test with --saccades off, everything works fine.

Full log of iKinGazeCtrl when the problem occurs here:
https://gist.github.com/lorejam/2620dc7f6378f568639f

Content of the configuration files that we are using:

```
$ cat /home/icub/.local/share/yarp/contexts/iKinGazeCtrl/config_imu_filter.ini
neck_position_control on
[cameras]
context   iCubLisboa01
file      icubEyes320x240.ini
[imu]
source_port_name /imuFilter/inertial:o
```

Our copy of ```/home/icub/.local/share/yarp/robots/iCubLisboa01/icubEyes320x240.ini``` is identical to the version on the icub-main repository.

/cc @gsaponaro

**Comment by pattacini** [comment]
Related to https://github.com/robotology/yarp/issues/634.
