### ISSUE TITLE
Implement changes done in IAmplifierControl, Ipid and IMotor 

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-main#247]
in CanBusMotionControl and embObjMotioncontrol.

see https://github.com/robotology/yarp/issues/645

**Comment by valegagge** [comment]
I implemented these changes in embObjMotionControl. I modified ethernet protocol also.
I still have to run test.

Implementing these changes in canBusMotionControl remains to be done. I assegn this issue to @randaz81

**Comment by pattacini** [comment]
@valegagge @randaz81 do you know what is the status of this quite old issue?
