### ISSUE TITLE
cannot find -licubmod

### ISSUE THREAD

**Issue by robertocalandra** [robotology/icub-main#248]
Hi,

I am trying to run some code I wrote some month ago (was working). However, when compiling now I get an error:

/usr/bin/ld: cannot find -licubmod
collect2: error: ld returned 1 exit status

In my code I use YARP_DECLARE_DEVICES(icubmod) to access the cartesian interface. However, multiple icub_mods are compiled. 
What am I doing wrong? Did something changed on how to call icubmod?

**Comment by pattacini** [comment]
Hi @robertocalandra,

Please refer to this announcement: https://github.com/robotology/QA/issues/68.

**Comment by robertocalandra** [comment]
Thanks.
