### ISSUE TITLE
Check how xml parameters are assigned by motionControl to the robot joints, taking in account the axisMap

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-main#255]
The following section (currently employed in icub torso xml) is critical because the requested `AxisMap` swaps few joints. The parameters which are sent to motor control boards are properly handled, because motionControl calls the yarp functions, which internally use the ->toHw() function provided by the interface helper. However, there exists few parameters, which are internally kept by motionControl and not sent to the motor control boards. For example, as reported in Issue #229, the `AxisName` parameter was obtained by yarp using the AxisMap, but motionControl was not using the inverted map in the internal storage. It is most likely that other parameter (e.g. `MotorType`) are affected by the same issue .

```
    <group name="GENERAL">
        <param name="MotioncontrolVersion">  2 </param>
        <param name="Joints"> 3 </param> 
        <param name="AxisMap">               2             0             1           </param>   
        <param name="AxisName">      "torso_yaw" "torso_roll" "torso_pitch"          </param>
        <param name="HasHallSensor">         1             1             1           </param>
        <param name="HasTempSensor">         0             0             0           </param>
        <param name="HasRotorEncoder">       1             1             1           </param>
        <param name="HasRotorEncoderIndex">  0             0             0           </param>
        <param name="Encoder">         182.044       182.044       182.044           </param>
        <param name="TorqueId">          0x0C          0x0C          0x0C            </param>
        <param name="TorqueChan">        0             1             2               </param>
        <param name="TorqueMax">         24            24            24              </param>
        <param name="JointEncoderType">  "AEA"          "AEA"       "AEA"            </param>
        <param name="RotorEncoderType">  "ROIE"         "ROIE"      "ROIE"           </param>
        <param name="JointEncoderRes">   4096          4096         4096             </param>
        <param name="RotorEncoderRes">   -14400        -14400       -14400           </param>
        <param name="RotorIndexOffset">  0             0            0                </param>
        <param name="Gearbox">           -100.00       -100.00      -100.00          </param>
        <param name="MotorType">       "BLL_MOOG"     "BLL_MOOG"   "BLL_KOLLM"       </param>
        <param name="MotorPoles">        8             8            8                </param>
        <param name="Verbose">      0   </param>
    </group>
```

**Comment by traversaro** [comment]
cc @nunoguedelha

**Comment by nunoguedelha** [comment]
Ciao @randaz81, @barbalberto , is there any update on this issue? This topic has been brought to our attention (estimation guys in DIC lab) as we require accurate information on the joint/motor coupling when identifying motor and joint friction parameters: https://github.com/robotology/robots-configuration/issues/39.

Our main concern is w.r.t. the couping matrix **matrixM2J**, and how it is mapped to the list of axis returned by  `yarp::dev::IAxisInfo::getAxisName(int j, yarp::os::ConstString & name)`.

### Example on the torso
`getAxisName()` returns the list of axes: torso_yaw, torso_roll, torso_pitch
Which matches the `AxisName` order in:
https://github.com/robotology/robots-configuration/blob/0ff6cee7bd4dee7811811e4d2eee29b16407234b/iCubGenova04/hardware/mechanicals/torso-eb5-j0_2-mec.xml#L8-L9
But the matrix lines follow the order R-P-Y which is the one in the `_AxisName` variable. This variable gets the axis names from the config files, remapped by `AxisMap`.
I was expecting to find the same remapped order in the axes names returned by `getAxisName()`, is this normal?

**Comment by barbalberto** [comment]
My two cents.
From the YARP point of view, the matrices are not mapped in any way. This is because the matrix is a _**single**_ data entry (big as much as it is required, but one piece of information). 

A matrix is referred to the whole controller (e.g. EMS), I don't know how it is filled. My guess is that the matrix is used by the firmware, so it is in the order preferred by the firmware, probably in the motor order.
