### ISSUE TITLE
check portaudio status

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-main#265]
From https://github.com/robotology/icub-support/issues/103 :

> Concerning portaudio : 
> I did sudo apt-get libportaudio0 libportaudio2 portaudio19-dev
> It allows yarp to be compiled with portaudio support, and "yarphear" to work on the pc104 live distrib, but some audio packets are lost...
> @randaz81 : didn't you correct some bug in portaudio (sources) a long time ? they were not pushed to the (portaudio) forge, did they ?

**Comment by reafrancesco** [comment]
@randaz81 I cannot recall any change in the portaudio. Maybe @barbalberto  changed few lines in the source code.

**Comment by barbalberto** [comment]
From git history there is no relevant changes since July 2014.
