### ISSUE TITLE
[robotInterface] Interesting sensor failures with new firmware and icub-main

### ISSUE THREAD

**Issue by rlober** [robotology/icub-main#271]
Not sure if this is exactly the best place for this issue but I figured because it happens in `robotInterface` why not.

Anyways, I recently updated iCubParis02 to the newest firmware and the latest `yarp` and `icub-main` and I am getting some interesting error messages from `robotInterface`. I say interesting because I have never seen them before and I am not sure where to start resolving them. After speaking with @julijenv it seems there have been some big changes to the firmware before the holidays and I am wondering if we are seeing some new bugs. Anyways here are some examples of these errors:

```
3015		32,457671		ERROR		AxisName not found
3493		36,865772		ERROR		Trying to get fullscale data from sensor 14 net [1]: no answer received or message lost (ch:0)
5206		212,515410		ERROR		AnalogWrapper: left_leg: Sensor returned timeout error (code 3).
```
*edit: these are only some of the errors...*

Here is the full log: [log_pc104_robotInterface_5489.txt](https://github.com/robotology/icub-main/files/81375/log_pc104_robotInterface_5489.txt)

Addmittedly these *could* be hardware related, but I am not entirely sure where to start with the debugging. 

For reference here is the `CMakeCache` of `icub-main` for pc104: [CMakeCache_icub-main-build-pc104.txt](https://github.com/robotology/icub-main/files/81368/CMakeCache_icub-main-build-pc104.txt)

cc: @randaz81 

edit:
Also. lots of warnings about syntax errors in the xml files 

```
2592		30,562498		WARNING		Invalid syntax while loading /usr/local/src/robot/source/icub-main/build-pc104/share/iCub/robots/iCubParis02/./icub_all.xml at line 1 . No DTD found. Assuming version robotInterfaceV1.0 

```

**Comment by Tobias-Fischer** [comment]
See e.g. https://github.com/robotology/icub-main/commit/8c0c9ae93a77565247adca016ef9f9138578fc5c for the `AxisName` problem.

No clue about the other stuff ;)

**Comment by Tobias-Fischer** [comment]
Ahh, for the warnings, add `<!DOCTYPE devices PUBLIC "-//YARP//DTD robotInterface 1.0//EN" "http://www.icub.org/DTD/robotInterfaceV1.0.dtd">` to the XML files. Again, https://github.com/robotology/icub-main/commit/8c0c9ae93a77565247adca016ef9f9138578fc5c shows an example.

**Comment by rlober** [comment]
@Tobias-Fischer 

Thanks for the info! I will make those changes.

**Comment by rlober** [comment]
**Updates: New error**
```
5130 311,814836 5 recv buffer overrun ( 500 >  500) 
```
After running for about 5 min `robotInterface` completely crashes pc104 and I get this `buffer overrun` error.

**Comment by drdanz** [comment]
Moved to robotology/icub-support#149. Closing this
