### ISSUE TITLE
[WARNING]Performance warning: You are using positionMove commands at high rate (< 80  ms). Probably position control mode is not the right control mode to use.

### ISSUE THREAD

**Issue by rlober** [robotology/icub-main#274]
Can anyone elaborate on this warning? And what is the control mode I should use? Position direct?

**Comment by francesco-romano** [comment]
Yes.
PositionDirect is the correct one.

When in position mode, the position reference is sent to a trajectory generator. Every time you update the reference the trajectory has to "start" again.
Instead if you use position direct, the reference goes directly to the PID control.

Maybe @randaz81 and @pattacini can explain this better than me

**Comment by rlober** [comment]
Hey @francesco-romano 

Thanks for the quick response! I have made the changes. Haven't tested yet but I think we can close this issue.
