### ISSUE TITLE
Missing library in the documentation

### ISSUE THREAD

**Issue by robertocalandra** [robotology/icub-main#277]
Hi,

I just performed a clean installation of yarp/icub-main on a new machine. It seems that the library libqt5opengl5-dev is required when compiling icub-main (but not by yarp). I think it would be good to add it to the documentation:
``` sudo apt-get install libqt5opengl5-dev```

**Comment by pattacini** [comment]
@francesco-romano it seems that it is not allowed to close an issue via a commit on a different repository.

Closing it manually.

**Comment by francesco-romano** [comment]
@pattacini the PR is still open, so probably this is why the issue was open.

**Comment by pattacini** [comment]
Yep, you're right, didn't notice the commit was in a PR :+1:
