### ISSUE TITLE
Update head IMU location for iCub Head v2 COM Express 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#285]
The new iCub v2 head with the new eletronics based on COM Express will have a different IMU. The sensor frame of this new IMU will be translated with respect to the frame of the old IMU: 
![image002](https://cloud.githubusercontent.com/assets/1857049/12678037/001201a6-c69d-11e5-8e8b-cf87bb020b47.jpg)

We then need to: 
- [ ] Update the documentation in http://wiki.icub.org/wiki/ICubForwardKinematics 
- [x] Add a new variant to [iCubInertialSensor](http://wiki.icub.org/brain/classiCub_1_1iKin_1_1iCubInertialSensor.html#a0d9da729f9e983a168a1bfaf72b083a6)
- [x] Modify the iKinGazeCtrl to use the correct IMU chain (even if the angular velocity model should not be affected).
- [ ] Modify the URDF model pipeline generator. 

cc @pattacini @matejhof @Mick3Lozzo

**Comment by barbalberto** [comment]
Is the IMU a new device? Do we have the yarp driver for it?

**Comment by randaz81** [comment]
* [ ] modify legacy SW (iDyn/wholeBodyDynamics/gravitycompensator) adding a new option --head_V2.5
* [ ] put in this page and in the official icub manual a link to the sensor datasheet.
* [ ] check the yarp devicedriver protocol

**Comment by traversaro** [comment]
The first robot with this head is now in the lab (`iCubGenova04`). The offset is just in position so it is not a big issue, but it should be solved.

**Comment by pattacini** [comment]
@traversaro, wilco soon

I'm also thinking of refactoring a bit the way version is specified, for `iKinGazeCtrl` at least, moving from 
```
headV2
```
to something like
```
hw-version 2.0
```

**Comment by traversaro** [comment]
The tricky part is modify the dh chain in http://wiki.icub.org/wiki/ICubInertiaSensorKinematicsV2 , but the automatic converter can help on this.

**Comment by pattacini** [comment]
Wouldn't we get away with less by resorting to `HN`? Is there any hitch on this?

**Comment by pattacini** [comment]
Working on this next **IFI**

**Comment by pattacini** [comment]
I'm done on my side

**Comment by traversaro** [comment]
@Mick3Lozzo told me f2f yesterday evening that the head recently mounted on `iCubGenova02` (the one with "python" cameras and the talking mouth) has a different IMU orientation w.r.t. to both the head v2.5 described and the previous version of the head. 
I am waiting more details from him, but it seems that in this case the IMU is mounted upside-down w.r.t. to previous heads, and consequently `gravityCompensator` and `wholeBodyDynamics` will not work on `iCubGenova02` until they are properly modified.

**Comment by pattacini** [comment]
I tend to take this new info as a bad **joke**, unless there are very very very good reasons to create yet another version.

**Comment by Mick3Lozzo** [comment]
It was due to simplify the assemblying and substitution of MC4-plus rack with an hinge system, but this solution has been abandoned because it's impractical (too many ca
![hing_system](https://cloud.githubusercontent.com/assets/15085666/22368757/8b33e484-e488-11e6-9d1c-04461bbe33fd.JPG)
bles and connectors).
The IMU has been repositioned in the previous position.

**Comment by traversaro** [comment]
I guess we can move this issue in icub-model-generator,  in https://github.com/robotology/icub-model-generator/issues/110 and close this issue. Feel free to reopen if necessary.

**Comment by traversaro** [comment]
For reference, this head is part of what is now called iCub 2.6 .
