### ISSUE TITLE
iCubGui: enhancing forces visualization

### ISSUE THREAD

**Issue by iron76** [robotology/icub-main#29]
In the iCubGui, the visualization of forces at the feet should be improved. In particular, at present forces are not visible since they are visualized under the floor. Moreover, when standing forces at the feet (~120N) are much bigger than those at the arms (typically in the order of 10N). Visualization results in a very long arrow very difficult to visualize. It would be good to implement a better visualization, e.g. arrows that scale not only in length but also in thickness or color.

**Comment by pattacini** [comment]
We can close this old request.
Agreed with @traversaro
