### ISSUE TITLE
Setting AxisName and AxisType, part 2

### ISSUE THREAD

**Issue by gsaponaro** [robotology/icub-main#294]
The **robotInterface** XMLs of some robots (e.g., ```iCubBarcelona01```) need ```AxisName``` and ```AxisType``` in order to get rid of RI error messages.

In the related issue https://github.com/robotology/icub-main/issues/273 we solved this problem for some robots, but not all.

/cc @jypuigbo @randaz81

**Comment by pattacini** [comment]
I honestly don't see how we're gonna commit ourselves to tackle this too generic issue, since it deals with the huge amount of robots we have.

Better to address the lack of this parameters case by case.
