### ISSUE TITLE
portaudio packages not installed in the icub live pc104 image

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#295]
@mbrunettini :
This morning on pc104 of the iCubGenova02, @DanielePucci was following the instructions at http://wiki.icub.org/wiki/Compilation_on_the_pc104 to compile yarp on the pc104, but we got an error because yarp could not find portaudio. 
We installed the necessary packets with `sudo apt-get libportaudio0 libportaudio2 portaudio19-dev` and now yarp is compiling fine.
As the portaudio device is mentioned in the official pc104 compilation instructions, we need to:
* Either mention that we need to install those packages in the documentation,
* or install those packages directly in the pc104 OS image,
* or add them as a dependency to `icub-common`. 

Using the apt-get portaudio packages could actually cause problems, see https://github.com/robotology/icub-main/issues/265 .

**Comment by mbrunettini** [comment]
What about adding those packages to the icub-common dependancies (as many others)?
@lornat75

**Comment by traversaro** [comment]
Option added to the bullet list.

**Comment by barbalberto** [comment]
Originally icub-common was meant to be used on laptop computers and pc104 was not using it.

**Comment by mbrunettini** [comment]
@barbalberto : you're right.
@traversaro : the package libportaudio-dev can be enough? The package libportaudio2 is already installed on PC1104 image. I'm trying to keep the image as thin as possible. Can we test it?

**Comment by traversaro** [comment]
I tested on the pc104 today first with `libportaudio-dev` and it was not enough to compile the `portaudio` driver in yarp.

**Comment by mbrunettini** [comment]
Added the required packages to the pc104 image. Available in next build.
Issue closed.

**Comment by mbrunettini** [comment]
A new live image with required package has been uploaded to icub.org website
