### ISSUE TITLE
Can't change light source position in iCub-sim world 

### ISSUE THREAD

**Issue by wainting** [robotology/icub-main#324]
Hi to all, 

I'm trying to change the light source position in the icub simulator world (sun position) on the back of the robot in order to enlighten directly the screen. I've found a code line in iCub_Sim.cpp `drawSkyDome(0,0,0,50,50,50);`, but it can only change the dimensions of the sky without performing rotation. I've thought alternatively to rotate the iCub position in order to take the sun on the back of robot but I can't find a way to to rotate the robot 'entirely' without changing every single part position.

Best Regards

Daniele

**Comment by vtikha** [comment]
@wainting, i apologise for the late reply, I just wanted to check if you managed to change the light source.

**Comment by pattacini** [comment]
Closing in the meantime.
