### ISSUE TITLE
calibrators and wrappers

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-main#326]
Check if the following snippet of configuration:

```
        <param name="CALIB_ORDER">(8 9 11 13) (10 12 14 15) </param>                       
        <action phase="startup" level="10" type="calibrate">           
            <param name="target">left_arm_mc_wrapper</param>    
        </action> 
```

is a correct alternative to the one currently used on the robots:

```
        <param name="CALIB_ORDER">(0 1 3 5) (2 4 6 7) </param>                       
        <action phase="startup" level="10" type="calibrate">           
            <param name="target">left_hand_mc</param>    
        </action>   
```

(The calibrator attaches to the **arm wrapper** instead of the **hand motor controller**)

**Comment by Tobias-Fischer** [comment]
Did someone try this? @randaz81

**Comment by Tobias-Fischer** [comment]
Any updates? @randaz81

**Comment by randaz81** [comment]
I think no one tested this on a iCub... even if other kind of robots (e.g. R1) use a similar calibration technique (so it should work, in principle).
Btw, I cannot remember anymore: why this issue is referenced by #334?

**Comment by Tobias-Fischer** [comment]
Ahhh cool, it might be good to try on a IFI day. The issue is referenced as it causes the following warning: `WARNING Device left_arm_mc is not implementing a yarp::dev::IRemoteCalibrator, therefore it cannot attach to a Calibrator device`

**Comment by barbalberto** [comment]
I don't remember the initial issue, anyway I can confirm that parametric calibrators work on wrappers, not motion control devices.

**Comment by valegagge** [comment]
I updated all calibration files of all ethernet robots.

@barbalberto Could you finish this work updating CAN robots also?
