### ISSUE TITLE
controlBoardDumper does not support RPATH

### ISSUE THREAD

**Issue by DanielePucci** [robotology/icub-main#336]
To launch control board dumper on OS X, I had to manually set the environmental variable 'DYLD_LIBRARY_PATH', i.e. on a terminal

~~~
export DYLD_LIBRARY_PATH=personalInstallPrefix/lib/
~~~

Hence, I fear that controlBoardDumper does not support RPATH and this should be fixed.

**Comment by francesco-romano** [comment]
Strange.
To me it seems ok.

Please reopen if it is still an issue.
