### ISSUE TITLE
changing root frame while using simCartesianControl 

### ISSUE THREAD

**Issue by tkelestemur** [robotology/icub-main#346]
Hi, 
As I understood from this [tutorial](http://wiki.icub.org/iCub/main/dox/html/icub_cartesian_interface.html) when I send a new pose to arm, inverse kinematic solver taking torso as the root frame. I would like to take the shoulder as the root frame. Is there anyway to make it possible without writing my own inverse kinematic app?

**Comment by pattacini** [comment]
Hi @tkelestemur 

If you block the torso joints by means of the [**`setDOF`**](http://www.yarp.it/classyarp_1_1dev_1_1ICartesianControl.html#a3198392b8807c1c293982301b658cc9c) service you won't have any movements of the torso. In this context, you still have to handle targets expressed in the standard reference frame, which I think isn't a big deal.

By contrast, if you're so eager to work in the shoulder's reference frame, you could retrieve the homogeneous transformation **H** that accounts for the shoulder's pose with respect to the root (use the axis version of the [**`getPose`**](http://www.yarp.it/classyarp_1_1dev_1_1ICartesianControl.html#a98b6776fcd71f7e3762bbc8c0afc0d42)) and then always multiply your target pose given in the shoulder's frame by **H** before feeding the cartesian controller.
