### ISSUE TITLE
iCub_SIM crashing on mac OS Sierra

### ISSUE THREAD

**Issue by gabriellap** [robotology/icub-main#386]
I am new to the iCub simulator and was trying to install it on the mac OS Sierra. Yarp seems to be working but the iCub simulator is crashing. I am getting the following error: 

[ERROR]
There seems to be a conflict with the  actElevation  configuration file 
[ERROR]Check the iCub_parts_activation.ini under $ICUB_ROOT/app/simConfig  
[ERROR]If it still does not work (update svn) and re-install the app folder
[ERROR]The iCub simulator will not start.. 

I have attached the report obtained from when the simulator crashed. Any feedback on what I might be doing wrong?

[icubsimreport.txt](https://github.com/robotology/icub-main/files/576223/icubsimreport.txt)

**Comment by claudiofantacci** [comment]
Hi @gabriellap, thanks for posting.

This issue was already posted and answered: https://github.com/robotology/icub-main/issues/382#issuecomment-258177095.

Closing here for duplication.
