### ISSUE TITLE
embObjAnalogSensor device does not report F/T sensors saturation even if the F/T sensor is saturating

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-main#403]
During some experiments on the `iCubGenova02` robot, we noticed that the F/T sensors start to saturate, but `embObjAnalogSensor` is only reporting an error in the second that it starts to saturate, and then it stops reporting any error for 10 seconds, even if the saturation is continuing. After 10 seconds, a new error message is printed.

Example error:
~~~
273	160,029882	ERROR	 from BOARD 10.0.1.8 (EB8), src CAN2, adr 13, time 9248s 897m 531u: (code 0x01000002, par16 0x0004 par64 0x0000023600000000) -> HW: strain values saturation. In p16 there is the channel involved, in p64 there are the saturation counts for the ``**last sec**``of both types (lower: LS32bits, upper MS32bits + 
~~~

@traversaro @DanielePucci @francesco-romano @gabrielenava  @marcoaccame @valegagge

**Comment by traversaro** [comment]
This used to work fine. We suspect there have been some regression either in `embObjAnalogSensor` or in the firmware.

**Comment by iron76** [comment]
😮

**Comment by marcoaccame** [comment]
The behavior has not changed and is correct. The diagnostics message is just misleading. 

It should be:

```
HW: strain values saturation. In p16 there is the channel involved, in p64 there are the 
saturation counts for the last 1000 readings of both types (lower: LS32bits, upper MS32bits
```

What I think is that the rate of the STRAIN is 10 ms, hence 10 ms * 1000 = 10 seconds.

**Comment by marcoaccame** [comment]
Now, discussion is what we want the diagnostics to behave: 
1. every 1000 times is happens (as now)
2. every second if it happens,
3. any other proposal

**Comment by S-Dafarra** [comment]
I would chose the second option. Since we will use it to debug high level control failures, having this information with a second delay at maximum, it will be much more effective.

**Comment by traversaro** [comment]
> The behavior has not changed and is correct. The diagnostics message is just misleading. 

For completeness, I clearly remember ( @francesco-romano @DanielePucci please correct me )  that some time ago the message was printed every second. Given that the behavior of the firmware/device did not change, I think that at some point the period of the STRAIN broadcast was modified from 1 ms to 10 ms .

**Comment by DanielePucci** [comment]
I sincerely remember 1s too, but I am not be completely sure.

**Comment by marcoaccame** [comment]
OK, I will change the FW in devel to emit these diagnostics messages at 1 Hz (if any saturation happens).

**Comment by DanielePucci** [comment]
👍

**Comment by pattacini** [comment]
@marcoaccame can this issue be considered finally addressed?

**Comment by marcoaccame** [comment]
yes. 
since ems.hex v 3.0 of 03feb17 (https://github.com/robotology/icub-firmware-build/commit/92f20750223b76f681efab1158926fb8f5eae94f).
