### ISSUE TITLE
FrameGrabberGui2 has a visual bug (see image)

### ISSUE THREAD

**Issue by barbalberto** [robotology/icub-main#416]
The gui has a visual bug as shown in the picture.
When frameGrabberGui is focused, an addictional small rectangular windows is displayed whose content usually is the desktop background or a portion of the gui itself.

Usually this side windows is opened at startup, if not clicking refresh button a few times will make it appear( and sometimes disappear)
![fgramegrabbergui-bug](https://cloud.githubusercontent.com/assets/4061020/22324587/87679c94-e3aa-11e6-9f5d-cb108acfd395.png)

Found on linux system (I don't know on win)

**Comment by pattacini** [comment]
I think this has been solved.
