### ISSUE TITLE
FindIPOPT.cmake fails on Ubuntu 16.10

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#418]
In particular, it puts `gfortran_NOTFOUND` and `quadmath_NOTFOUND` in `IPOPT_LIBRARIES`, causing then a link error.

**Comment by traversaro** [comment]
Workaround commited in https://github.com/robotology/icub-main/commit/278d1ebffd89edc8af565789b93600bb347cfd38 .

**Comment by drdanz** [comment]
Filed an issue on ubuntu bug tracker: https://bugs.launchpad.net/ubuntu/+source/coinor-ipopt/+bug/1659835

**Comment by traversaro** [comment]
The workaround is working fine, and an upstream issue has been reported. I think we can close the issue.

**Comment by traversaro** [comment]
See also : https://github.com/robotology/idyntree/issues/329#issuecomment-311252008 .
