### ISSUE TITLE
Jacobian in the ICub Simulator 

### ISSUE THREAD

**Issue by LakshithaPW** [robotology/icub-main#423]
Dear All,

I was wondering anyone could help me to find the Jacobian in real time for the iCub Simulator ?
I want to control the end effector of the iCub given a specified task space velocity. 

Thanks in advance

**Comment by pattacini** [comment]
Issue moved to [robotology/QA #185](https://github.com/robotology/QA/issues/185) via [**ZenHub**](https://www.zenhub.com/)
