### ISSUE TITLE
http://wiki.icub.org/wiki/Downloads is outdated

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#429]
http://wiki.icub.org/wiki/Downloads is only referring to the release 1.4.0 of iCub, but the release 1.6.0 is out since November.

**Comment by drdanz** [comment]
Should we add this page to the release instructions or is it there already?
CC @mbrunettini

**Comment by traversaro** [comment]
Already added in https://github.com/robotology/icub-main/pull/351 .

**Comment by traversaro** [comment]
The issue is actually still there for iCub 1.8.0 : http://wiki.icub.org/wiki/Downloads . 
cc @drdanz @mbrunettini @pattacini

**Comment by mbrunettini** [comment]
@drdanz made some changes in the doxigen yesterday.

**Comment by traversaro** [comment]
@drdanz Any news? 
In the meanwhile I updated the http://wiki.icub.org/wiki/Downloads page.

**Comment by aerydna** [comment]
can we close this issue or is still valid?
@traversaro @drdanz

**Comment by traversaro** [comment]
After the release 1.10.0, the Wiki page is outdated again, see http://wiki.icub.org/wiki/Downloads .
cc @drdanz @lucaTagliapietra

**Comment by mbrunettini** [comment]
page fixed

**Comment by traversaro** [comment]
The page is now outdate after the release 1.12.0, see http://wiki.icub.org/wiki/Downloads .

**Comment by mbrunettini** [comment]
links updates
