### ISSUE TITLE
Issue compiling iCub contrib

### ISSUE THREAD

**Issue by KatePaulinne** [robotology/icub-main#431]
Hi,

Sorry for posting this again here, I posted an issue a few days ago on robotology/icub-contrib-common Github repository but had no reply..

I get the below error when trying to compile icub-contrib-common in CMake when following Windows installation guide. Could it be because I installed YARP (2.3.66) and iCub (1.4.0) from binaries rather than sources? I tried adding  the path to environment variable as the error suggests however it didn't work.. As you can see the below configures despite the error so I was able to generate project files but when I try to compile it in Visual Studio it errors as well.. 

Would anyone be able to help with this, please? I would be very grateful for suggestions.

_

> Installation prefix is different from YARP: no file will we be installed into path.d folder, you need to set YARP_DATA_DIRS environment variable to C:\Program Files\robotology\yarp-2.3.66\share\yarp;C:\Program Files\robotology\icub-1.4.0\share\iCub;C:/Program Files/ICUBcontrib/share/ICUBcontrib;C:/Program Files/ICUBcontrib/share/ICUBcontrib
> Configuring done

_

Thanks,
Kate

**Comment by pattacini** [comment]
This is a duplication of https://github.com/robotology/icub-contrib-common/issues/6.
