### ISSUE TITLE
yarprobotinterface -> seg fault

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-main#436]
Every time CTRL+C is sent yarprobotinterface returns "Segmentation fault (core dumped)" and then you must reset the boards to run it again

**Comment by pattacini** [comment]
I'm afraid then that the problem involves also the FW.

cc @robotology/firmware-developers

**Comment by pattacini** [comment]
Issue moved to [robotology/yarp #1168](https://github.com/robotology/yarp/issues/1168) via [**ZenHub**](https://www.zenhub.com/)
