### ISSUE TITLE
CMake is not exporting version information

### ISSUE THREAD

**Issue by Tobias-Fischer** [robotology/icub-main#437]
Hi,
It seems that the versioning information is not properly propagated. If I do (in an external project):
```
find_package(ICUB)
message(STATUS "iCub is version: ${ICUB_VERSION}")
```
Then `${ICUB_VERSION}` is just an empty string. For other packages (like YARP) the very same code snippet works nicely.

Best, Tobi

**Comment by drdanz** [comment]
Fixed in b2dad4f
