### ISSUE TITLE
Missing CREATE_LIB_MATH=ON in Yarp is not detected

### ISSUE THREAD

**Issue by diegoferigo** [robotology/icub-main#443]
When `yarp` is not compiled with `CREATE_LIB_MATH=ON`, `icub-main` fails building during the `src/libraries/learningMachine` libraries compilation.

I don't know if it is a `yarp` bug, that does not properly export that option, or `icub-main` that doesn't check it.

cc @drdanz @traversaro

**Comment by traversaro** [comment]
This should be handled by https://github.com/robotology/icub-main/blob/d38c580c4792518068efea6ce0713530af7b1b12/CMakeLists.txt#L38 , I don't know if something is going wrong there.

**Comment by pattacini** [comment]
@drdanz any comment on this? Maybe the variable `YARP_HAS_MATH_LIB` is no longer handled?

**Comment by drdanz** [comment]
Fixed by robotology/yarp@8f67a07
