### ISSUE TITLE
Errors in build-tree and install-tree includes

### ISSUE THREAD

**Issue by diegoferigo** [robotology/icub-main#444]
When building the `devel` branch against `yarp:dev`, having installed `icub-main:master`, the build fails with the following error:
```
In file included from /home/dferigo/iit/sources/icub-main/src/tools/fingersTuner/main.cpp:95:0:
/home/dferigo/iit/local/include/iCub/ctrl/tuning.h:166:16: error: 'IOpenLoopControl' in namespace 'yarp::dev' does not name a type
     yarp::dev::IOpenLoopControl *iolc;
                ^
In file included from /home/dferigo/iit/sources/icub-main/src/tools/fingersTuner/main.cpp:95:0:
/home/dferigo/iit/local/include/iCub/ctrl/tuning.h:361:16: error: 'IOpenLoopControl' in namespace 'yarp::dev' does not name a type
     yarp::dev::IOpenLoopControl *iolc;
                ^
src/tools/fingersTuner/CMakeFiles/fingersTuner.dir/build.make:71: recipe for target 'src/tools/fingersTuner/CMakeFiles/fingersTuner.dir/main.cpp.o' failed
```
Considering that `/home/dferigo/iit/sources/` is the sources tree, and `/home/dferigo/iit/local/` is the install-tree, `icub-main` includes the installed header and not the build-tree header.

cc @drdanz @traversaro

**Comment by traversaro** [comment]
There was a similar issue in iDynTree : https://github.com/robotology/idyntree/issues/52 .
It probably boils down to the order with which the include directories are passed to the compiler:
https://github.com/robotology/icub-main/blob/master/src/tools/fingersTuner/CMakeLists.txt#L12 . 
Always having the build include directories as the first one should solve the issue.

**Comment by pattacini** [comment]
Discussed in person with @traversaro 
Hopefully fixed by https://github.com/robotology/icub-main/commit/fd6f2eb6d869d0a5c68f5c24a2342b4bcb85b4eb

**Comment by diegoferigo** [comment]
Thanks Ugo for the quick fix, I confirm it works!

**Comment by traversaro** [comment]
Also related to https://github.com/robotology/ycm/issues/29 .
