### ISSUE TITLE
Update documentation on Linux on the iCub head to cover the non-pc104 case

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#456]
Currently the documentation on how to manage the OS on the iCub head computer is this one: 
http://wiki.icub.org/wiki/The_Linux_on_the_pc104 . This documentation should be updated to cover the case of iCub robots with the new head without the pc104. As far as I know, the robots affected by this are: 
* `iCubGenova02`
* `iCubGenova04` 
* `iCubLausanne02` 
but it is possible there are more models affected. 

cc @lornat75

**Comment by pattacini** [comment]
Updated documentation available at https://icub-tech-iit.github.io/documentation/icub_operating_systems/pc104/icub-live/.
