### ISSUE TITLE
Documentation of canBusSkin and embObjSkin devices

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#465]
For people working on the skin, it would be really convenient to have a documentation of the parameters supported by the `canBusSkin` (class `CanBusSkin`) and `embObjSkin` (class `EmbObjSkin`) similar to what we have for the [`canbusanalogsensor`](http://wiki.icub.org/brain/group__canbusanalogsensor.html) and for the [`canbusinertialmtb`](http://wiki.icub.org/brain/group__canbusinertialmtb.html) devices.

**Comment by traversaro** [comment]
cc @joankangro

**Comment by valegagge** [comment]
Currently you can find how to configure embObjSkin in the robots configuration template files.
See
[https://github.com/robotology/robots-configuration/tree/master/iCubTemplateV3_0/hardware/skin](https://github.com/robotology/robots-configuration/tree/master/iCubTemplateV3_0/hardware/skin)

In the future, we will integrate in doxigen documentation of icub devices.

**Comment by randaz81** [comment]
Similar to #477

**Comment by pattacini** [comment]
The skin-related device drivers will undergo a general overhaul, which will entail that we provide documentation as well.
