### ISSUE TITLE
object creation slows down iCub_SIM 

### ISSUE THREAD

**Issue by tanismar** [robotology/icub-main#47]
Hi all, 
I am performing an experiment on the simulator in which an object on the table is moved by the iCub. Originally, for every new trial I just deleted the moved object and created a new object on the original position. When running this experiment for long periods of time, after around 30 -40 trials, that is 30-40 new objects, the simulator slowed down considerably, going from a recommended time step of 8-9ms at the beginning of the experiment up to 35-40 ms after those trials. Modifying the code so that the object was moved instead of created anew solved the problem, but the issue still remains that, even if they are deleted, the creation of objects slows the simulator down. 
Any idea of why this can be, and/or how to solve it?
Best

**Comment by pattacini** [comment]
@tanismar any update on that?

**Comment by tanismar** [comment]
Yes and no: Creating new objects still slows down the simulator, because apparently even if the object in the simulator gets deleted, information about it is kept and accumulates. I talked with Vadim about this but he didn't know exactly where or which information was kept, and given that we are moving to Gazebo anyway, we though it was better to find a work around for the moment. In my case, it was that instead of deleting and creating again the objects every trial of the experiment, I just move them to the original position. This solved my problem and permitted me to run the experiment for large amount of trials without noticeable slowdowns.

**Comment by pattacini** [comment]
ok, thanks, closing then...
