### ISSUE TITLE
camCalib crashes (mostly left eye)

### ISSUE THREAD

**Issue by claudiofantacci** [robotology/icub-main#478]
While working on Blacky, the (left eye) `camCalib` keeps crashing regularly after some times.
Together with @giuliavezzani, we have experienced this issue while extensively using images (i.e. a lot of connection) from the left eye.

This issue is to keep track to this issue and eventually to trigger discussion.
@Nicogene and I will do some tests trying to log data and understand where the problem is.

**Comment by randaz81** [comment]
Please specific also the carrier used for connections.
I remember that I saw similar crashes sometime ago using exotic stuff such as `shmem`... 
And I'm not 100% sure about mjpeg, too.

**Comment by Nicogene** [comment]
Input connections : `tcp`
Output connections : `udp`

Why this choice is a mystery 😅

**Comment by pattacini** [comment]
@Nicogene `tcp` is applied to a single connection (`framegrabber` ➡️  `camCalib`), whereas `udp` is applied to multiple connections since `camCalib` serves many downstream modules.

I think this was the original rationale, perhaps ;)

**Comment by Nicogene** [comment]
Ok for `tcp` (maybe it is better `fast_tcp` ? Do we need a syncro with the sender?), but the most efficient carrier for the **one-to-many** connections is `mcast` that at the time in which the xml was created was full of 🐞 but now it is a 🚀  😉

**Comment by pattacini** [comment]
I agree with you @Nicogene for `mcast`.
As of now, please let's stick to `tcp`.

**Comment by Nicogene** [comment]
The first thing to do is to check, when this problem happens, if `/icub/cam/left` is actually streaming images. If doesn't, it is a problem in dragonfly2 cameras (HW ? SW?), otherwise it is `camCalib` fault  🕵️

**Comment by claudiofantacci** [comment]
> Ok for tcp (maybe it is better fast_tcp ? Do we need a syncro with the sender?), but the most efficient carrier for the one-to-many connections is mcast that at the time in which the xml was created was full of 🐞 but now it is a 🚀 😉

This would also be worth trying, but 

> As of now, please let's stick to tcp.

This is also valid, at least in the short term, but @Nicogene, @giuliavezzani and I can do some tests with our setting to check this out.

**Comment by claudiofantacci** [comment]
Do we have any update on this?
@Nicogene
