### ISSUE TITLE
Revamp documentation on the iCub's FT Sensor 

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#482]
**Note: this issue is mostly about documentation about the FT Sensor mounted on the iCub. As this documentation is now hosted at http://wiki.icub.org/wiki/FT_sensor , I will document revamping the documentation of the FT Sensor here. If you can suggest any other tracker that could be more indicated to keep track of this, please comment and suggest it, thanks.**

**Comment by traversaro** [comment]
* [ ] Update broken links in http://wiki.icub.org/wiki/FT_sensor
* [ ] Add documentation on STRAIN2

**Comment by pattacini** [comment]
Moved internally.
