### ISSUE TITLE
Icub_SIM image processing:

### ISSUE THREAD

**Issue by drdanz** [robotology/icub-main#485]
@muhammadbilalababsi commented on [Sun Jan 14 2018](https://github.com/robotology/yarp/issues/1511)

Hi everyone. i am currently working on image processing for icub_SIM and i got a sample code for it. can anyone please help me that what is purpose of this line of code in python. as This symbol(<>) seems strange to me. 

if left_eye_yarp_image.getRawImage().__long__() <> left_eye_img_array.__array_interface__['data'][0]:

Thanks

**Comment by drdanz** [comment]
Moved to icub-main

**Comment by barbalberto** [comment]
That's a python question, not yarp, nor icub.

https://stackoverflow.com/questions/16749121/what-does-mean-in-python
