### ISSUE TITLE
PWM measurements are streamed from the robot in percentage over the full scale, but all the other parameters in API and in configuration files are using PWM as raw integers

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#497]
See https://github.com/robotology/yarp/issues/1556#issuecomment-367955842 .

@traversaro wrote: 
> I see, the semantics of the PWM measurement changed during the migration from PIDOutput to PWM interfaces (https://github.com/robotology/yarp/pull/1145). 
>
> The problem is now that the estimation software will estimate the PWM (in percentage) ---> Torque (Nm) coefficient, but the interface for setting torque control parameters and the embObj configuration files wants the Torque (Nm) ---> PWM ( as raw integer ) coefficient (or something similar, see https://github.com/robotology/robots-configuration/blob/master/iCubGenova04/hardware/motorControl/right_leg-eb9-j4_5-mc.xml#L86 ). However, this definitely a icub-main issue and only partially a YARP issue (the only part of this issue related to YARP is the precise semantics of the `ktau` parameter http://www.yarp.it/classyarp_1_1dev_1_1MotorTorqueParameters.html#a7099e7a5441c7c555dd4c936fae23e46 .

**Comment by traversaro** [comment]
@valegagge wrote:

> @traversaro you are right!
> 
> We need to update API (or use new interface) in order to use PWM in %.
> 
> @nunoguedelha
> You can use the full scale in the configuration files to convert from raw to %.
Use parameterfullscalePWM; see https://github.com/robotology/robots-configuration/blob/8423a4d9ef054ed579b67dccac1cc34ec9105e5c/iCubTemplates/iCubTemplateV4_0/hardware/mechanicals/body_part-ebX-jA_B-mec.xml#L12 .

> As a temporary solution, I can add a remote variable for fullscalePWM, but I can't implement it immediately

**Comment by randaz81** [comment]
fixed by https://github.com/robotology/yarp/pull/1612
