### ISSUE TITLE
Installing older icub/yarp versions

### ISSUE THREAD

**Issue by stango12** [robotology/icub-main#506]
I want to use a really old icub/yarp version (icub 1.1.13, yarp 2.3.22) on an ubuntu VM and was wondering what the process was for using it instead of the newer versions. Would I also have to install the dependencies in an older version? If so, how would I know what version to install/how? Thanks for any help!

**Comment by drdanz** [comment]
Hello @stango12,

YARP 2.3.22 sources and binaries are available [here](https://sourceforge.net/projects/yarp0/files/yarp2/yarp-2.3.22/)
iCyb 1.1.13 sources and binaries are available [here](https://sourceforge.net/projects/robotcub/files/iCub-main/iCub-main-1.1.13/)

The binary releases contain all the dependencies you need.

Good luck!
