### ISSUE TITLE
iCub_SIM control stability problem

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#522]
Following up the latest modifications that Yarp has been undergoing, `iCub_SIM` does no longer seem to be running properly under Windows in terms of control stability.

Find below an example where the head moves responding to the `iKinGazeCtrl` commands. It is evident how the control stability is somewhat compromised.

![1unybw0j4n](https://user-images.githubusercontent.com/3738070/40587042-554ed3a4-61ca-11e8-9011-3049481fa4a8.gif)

Likewise, I've seen similar behaviors along with Cartesian control, as if the latency of control loop has been increased somehow.

Did anything change with respect to the low-level PID gains/control?

Weirdly, the control seems to be ok under Linux instead.
I can provide more details.

cc @randaz81

**Comment by pattacini** [comment]
This is becoming quite an important issue that needs our attention!

**Comment by lornat75** [comment]
do we have latency tests we can run on windows?

**Comment by lornat75** [comment]
@Nicogene

**Comment by Nicogene** [comment]
We should investigate which are the differences from linux and windows.
The only changes made on the communication part are the one of `TCP_CORK`, I don't know if in windows is defined, if not defined the tcp carrier is the "old" one.

**Comment by lornat75** [comment]
it would not harm to run a few latency tests win2win, win2linux and linux2win

**Comment by pattacini** [comment]
I've just done a quick test again on this and "_automagically_" the problem has disappeared: everything's working well again.

Is anyone aware of any possible dev/fix that sorted this out? @lornat75 @drdanz @Nicogene @randaz81

**Comment by Nicogene** [comment]
Unfortunately I'm not, it came from nowhere and returned to nowhere :sweat: :beetle: :alien:
