### ISSUE TITLE
FindACE w/o YARP_MODULE_PATH

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#534]
Since `YARP_MODULE_PATH` is deprecated, to find `ACE` (used by e.g. `embObj`) we would need to rely on `YCM`, meaning that `YCM` should be considered from now on a new strict dependency in our pipeline, also affecting binaries, documentation...

cc @traversaro @drdanz @lornat75 @mbrunettini @vtikha @claudiofantacci

**Comment by claudiofantacci** [comment]
Since this action may require some extra effort, I'm wondering if it is worth setting up a f2f meeting to opt for proper actions.

**Comment by Tobias-Fischer** [comment]
Is there any news for that issue? Sooner or later people will run into issues, for example see https://github.com/robotology/yarp/issues/1831 which is closed but not fixed ..

**Comment by drdanz** [comment]
> Don't know when we've planned to consider YCM a strict dependency.

About 4 years ago...

**Comment by pattacini** [comment]
@drdanz the question was related to our packages, I suppose 😉

**Comment by pattacini** [comment]
I wouldn't put YCM in `icub-main` honestly, it's quite a dirty solution.
Let's deliver it in the new packages and, in the meanwhile, if YCM is required travis-wise, then it could be still downloaded in the server easily.

**Comment by drdanz** [comment]
> I wouldn't put YCM in icub-main honestly, it's quite a dirty solution.

That's the reason why it's not there yet :rofl:

**Comment by pattacini** [comment]
`ycm` is mandatory for `icub-main` sincce distro 2020.02.
