### ISSUE TITLE
RobotMotorGui fixes and improvements

### ISSUE THREAD

**Issue by barbalberto** [robotology/icub-main#54]
A reminder for some thing to be fixed/improved in the robotMotorGui.

1) **Bug**: If one part is not available, it crashes instead of closing down properly.

2) Sequence tabs
2a)**Bug**: The gui opens ports for the sequence tab with improper name like:
    registration name /robotMotorGui/left_arm/sequence:o 
without the trailing number like the other ports, like in
   registration name /icub/robotMotorGui0/left_arm/command:o 

when opening 2 motorguis, that will result in an address conflict and the second gui will not open the port. As a conseguence the sequence tab will **silently** not work. I propose to change those portNames adding at least the number and the robotname (like other ports).

2b) *Optional improvement*: The sequence tab are very rarely used; can those ports be opened only when actually needed by the user? This will save resources and will not pollute the port name list

3) Uniform way of calling port names: (*User-friendlyness improvement*)

The 'de facto' convention for opening ports is like:
/applicationName/[robotName]/partname/... which makes the related port easy to spot in the yarp name list output and to manually write from terminal.

here we have:
 /icub/robotMotorGui0/left_arm/...    // application name in the middle, mixes port from robotInterface and from motorGui
/robotMotorGui/left_arm/          // no number and no robot name, so different synatx from other ports from the same executable.

Can we make those names uniform using a syntax like the following?

/robotMotorGui<N>/robotName/left_arm/command:o 
/robotMotorGui<N>/robotName/left_arm/rpc:o
/robotMotorGui<N>/robotName/left_arm/state:i
/robotMotorGui<N>/robotName/left_arm/sequence:o 

Since we can use the robot and one or more simulator at the same time, the robotName is always useful, the sequence port shall follow.

**Comment by pattacini** [comment]
I'm closing this issue since now any dev must be carried out with the brand new `yarpmotorgui`. I feel that some of the fixes/improvements you mentioned have been already in place there.
