### ISSUE TITLE
skinManager drift compensation not working for foot patches

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#55]
Currently the (thermal) drift on the skin tactile sensors is compensated through the skinManager module. Apparently its behaviour is not optimal for the foot skin patches, because if the robot is in double support, after some time (30 seconds/1 minute?) the skin compensated output goes to zero on most of the taxels. 

I did not investigated appropriately this issue,  but I guess that the root of the problem is that the compensator for the drift of the skin was originally designed under the assumption that no contact on the skin was persistent in time, and it was implemented as an high pass filter to discriminate between low frequency components (due to drift) and high frequency components (due to contacts). Unfortunately this assumptions does not hold any more for the foot contacts. 

I don't plan to commit time to fix this issue in the short  term, but perhaps a preliminary discussion on how to solve this problem can be useful. I guess for sure that @andreadelprete , the original author of skinManager, can provide useful hints.

**Comment by traversaro** [comment]
@massimoregoli What is the state of this issue? The temperature compensation is now working on the skin ?

**Comment by massimoregoli** [comment]
I didn't check (I just work on fingertips and they are not affected so much by the temperature) but @maggia80  told me it is working
