### ISSUE TITLE
Default  ICUBMAIN_COMPILE_SIMULATORS to OFF on macOS

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#551]
As far as I understand, `iCub_SIM` has not been working since years on macOS. I wonder if then it makes more sense to default the `ICUBMAIN_COMPILE_SIMULATORS` CMake option to `FALSE` on macOS, to avoid compilation problems such as the one described in https://github.com/robotology/icub-main/issues/514https://github.com/robotology/icub-main/issues/514 .

**Comment by Nicogene** [comment]
100% agree, @claudiofantacci fixed the compilation but it doesn't work.
We should disable it until someone fixes it, but I'm afraid it will be quite tough

**Comment by vtikha** [comment]
I also fully agree
