### ISSUE TITLE
Travis on devel is failing  

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#564]
Probably due to the old version of OpenCV running on Travis, see https://github.com/robotology/idyntree/issues/511 . As I guess this is intentional, we can either switch off Travis for icub-main, or migrate it to run on Xenial or Bionic using the new docker-based template, see https://github.com/robotology/how-to-export-cpp-library/issues/29 and https://github.com/robotology/how-to-export-cpp-library/pull/36 .

**Comment by pattacini** [comment]
Cool 👍
