### ISSUE TITLE
frameGrabberGui2 segmentation fault

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-main#565]
unable to run the GUI..
**head OS** : iCub OS version 8.0.18.04-20161123 based on Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-43-lowlatency x86_64)
**server OS**: ubuntu 18.04.1 LTS

![pastedimage](https://user-images.githubusercontent.com/6638215/50824309-87dbc700-1336-11e9-97e7-9dfe1579cc05.png)

**Comment by pattacini** [comment]
Thanks @davidetome for reporting.

How's your setup like in terms of `yarp` and `icub-main` software configurations? In particular, are you using binaries (which version?) or `master` / `devel` branches compiled?

**Comment by davidetome** [comment]
Hi @pattacini , thanks for quick reply.
I'm using  master branches compiled..
![image](https://user-images.githubusercontent.com/6638215/50829397-b2cd1780-1344-11e9-81d8-dc8f1a3e1f8e.png)

**Comment by davidetome** [comment]
I tried to:

1) switch to devel branch (both on icub an yarp)
2) using a server with ubuntu 16.04 LTS

the behavior is the same; GUI opens only if yarpdev is not running on the head. Otherwise i get segmentation fault

**Comment by davidetome** [comment]
this is the error message caught by @pattacini  debugging framegrabbergui2:

ASSERT failure in QList<T>::at: "index out of range", file /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h, line 541

Thread 1 "frameGrabberGui" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

**Comment by pattacini** [comment]
@Nicogene would you be available to help on this?

**Comment by lornat75** [comment]
have you tried to replicate the problem on another machine/setup? is the framegrabber gui working on the iCub setups?

**Comment by pattacini** [comment]
On Blacky setup, the GUI works normally, barring a few seldom crashes.
I talked f2f to @Nicogene who said he is aware that the GUI seg-faults are due to flaw exceptions handling while processing received messages from the grabber.

**Comment by davidetome** [comment]
ok, now everything works properly. Thank you all

**Comment by pattacini** [comment]
Great! Many thanks to @Nicogene 👍
