### ISSUE TITLE
Enable compilation warning if return statement is missing in not void function

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-main#589]
I think it could be useful get a compilation warning (even an error) when missing the return statement in a function with not void return type.

I verified that yarp gives such warning while icub-main doesn't. [Linux environment] 

Is it possible to modify the cmake file in order to get such warning also in icub-main?

**Comment by valegagge** [comment]
cc @drdanz

**Comment by traversaro** [comment]
Just for your information: if you want to add such a warning  also locally on your machine build, you can simply add the  `-Wreturn-type` flag to the `CMAKE_CXX_FLAGS` CMake cache variable.
