### ISSUE TITLE
ALLOW_IDL_GENERATION compilation issue?

### ISSUE THREAD

**Issue by randaz81** [robotology/icub-main#59]
I do not have a complete understanding of this, but I just noticed that if I start from scratch, icub-main fails to compile if ALLOW_IDL_GENERATION is off (default value). After the first compilation, I can put it off again.
However:
* ALLOW_IDL_GENERATION is hidden in the icub-main advanced cmake menu
* The default value is off, and the documentation does not explain what to do.
* CREATE_IDLS on yarp cmake manke is also off by default.
Maybe we can do something to make this more clear?

**Comment by pattacini** [comment]
very long discussion; did we manage to solve the issue?
