### ISSUE TITLE
embObjIMU has irregular rate

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-main#595]
Trying the changes added in #592 I noticed a worse behaviour of `iKinGazeCtrl` while using the `imurfe` data instead the "old" `imuBosch_BNO055` attached via i2c.

I dumped the dt of data received and here is the result:

![image](https://user-images.githubusercontent.com/19152494/63028528-4ce2d880-beaf-11e9-877d-f2afe81708f9.png)

The upper plot represent the dt using the `imuBosch_BNO055` attached to the pc104, the other one the `imurfe` using `acquisitionRate` = 10.

EDIT: these numbers have been taken from the `iKinGazeCtrl`, then the timestamp is the one set by the embObjIMU device, then not the one coming from the board.

cc @traversaro  @pattacini

**Comment by Nicogene** [comment]
Today I performed a more accurate measure on `iCubGenova02` of the performance of the `imu-rfe` dumping the timestamp coming from the board and here the result:

## Plot
![image](https://user-images.githubusercontent.com/19152494/64013132-6dea3100-cb1f-11e9-89bb-c8be505b261e.png)


## Histogram
![image](https://user-images.githubusercontent.com/19152494/64013056-4d21db80-cb1f-11e9-9d3e-98ea43320b69.png)

**Comment by Nicogene** [comment]
For excluding any type of interference I performed the same test running only the device of the `imu-rfe` on `iCubGenova02` and here the results:

## Plot
 
![image](https://user-images.githubusercontent.com/19152494/64018150-f1118400-cb2b-11e9-84a4-05a90995fbe8.png)

## Histogram

![image](https://user-images.githubusercontent.com/19152494/64018196-0ab2cb80-cb2c-11e9-8d9b-16000c51263a.png)

**Comment by marcoaccame** [comment]
OK @Nicogene, we shall investigate the problem together. I get in touch w/ you soon.

**Comment by Nicogene** [comment]
The results has been confirmed also on the minimal setup, ms board-rfe-laptop

![image](https://user-images.githubusercontent.com/19152494/64349633-967a9b00-cff7-11e9-9b2a-40581ba058d1.png)


![image](https://user-images.githubusercontent.com/19152494/64349678-a5f9e400-cff7-11e9-9b15-2c8b7c4f968d.png)

**Comment by Nicogene** [comment]
@triccyx  and me extracted the statistics of the acquisition time of the CAN and here is the histogram(~ 2000 samples):

![image](https://user-images.githubusercontent.com/19152494/66583157-2aa1ca00-eb83-11e9-8bb4-665d7e9c08ee.png)

And here is the plot of the acquisition time:

![image](https://user-images.githubusercontent.com/19152494/66583517-c9c6c180-eb83-11e9-8aa2-7947223ab43f.png)

**Comment by Nicogene** [comment]
Me @triccyx @marcoaccame and Giorgio Zini analyzed the behavior of the i2c bus of the rfe board, to which is attached the imu Bosch BNO055. 

We measured with the oscilloscope the lines `SCL`(clock) the `SDA`(data), and the CAN channel that send the data to the `mc4plus` board as soon as the data is ready.

## `SCL` periodicity

First of all we checked that the clock signal is raised up with a period of 10 ms as you can see from the following figure(yellow line).

![SCL-10msec 001](https://user-images.githubusercontent.com/19152494/66988152-54e31280-f0c2-11e9-86f9-d584b0746e5b.png)

## CAN transmission

Then we checked that effectively the CAN(blue line) starts transmitting just after the end of the `SCL` signal(yellow line). 

![SCL-CAN 001](https://user-images.githubusercontent.com/19152494/66988519-f4080a00-f0c2-11e9-9275-14faa6aa6fa4.png)

Zooming in it is possible to see that the delay between the end of the `SCL` and the start of `CAN` transmission is very little.

![SCL-CAN 003](https://user-images.githubusercontent.com/19152494/66988587-17cb5000-f0c3-11e9-878c-7e066e034ad6.png)

## `SCL` variance

We verified that the clock signal is triggered every 10 ms, but we observed also the duration of this signal respect also to the SDA channel(blue line). 
We observed that sometimes the data is ready and the acquisition from the imu lasts less, other times the clock is stretched for waiting the imu.

### "Short" acquisition

![SCL-SDA 005](https://user-images.githubusercontent.com/19152494/66989187-21a18300-f0c4-11e9-9468-c61988465f84.png)

### "Long" acquisition

![SCL-SDA 004](https://user-images.githubusercontent.com/19152494/66989208-3120cc00-f0c4-11e9-8f6a-1eaef4b069ec.png)

## Conclusion

With the oscilloscope we observed the same time variability in the acquisition of the data through the i2c bus that we spotted with the various statistical analysis of the timestamp done at higher level.

I personally checked the functionality of software that uses the imu such as `iKinGazeCtrl`, `wholeBodyDynamics` and `gravityCompensator` and they work fine also with the imurfe.

We saw that the i2c speed of SCL on rfe board is the standard one (100 KHz), we don't know if the the i2c of the old imu attached of PC104 is set or not in fast mode(up to 400 KHz). 
Increasing the speed could reduce the variability we observed, but probably it requires an analysis in the electronics (e.g. pull-up resistors etc).

Moreover we found out that probably the way the timestamp is take by the device of the old imu(see https://github.com/robotology/yarp/blob/1c5d43a79578df971791a1b5f9ee61c18bb06f41/src/devices/imuBosch_BNO055/imuBosch_BNO055.cpp#L613) hides this variability of i2c bus.

If we are interested we can move that line and **after** the read function and measure again the timestamp of the old imu. Otherwise I think we can close this issue.

cc @pattacini @maggia80 @traversaro

**Comment by Nicogene** [comment]
We tested the performances of imurfe respect to the old imu bosch attached to the pc104 and we observed they behave in the same way.

This supports the hypothesis that the probably both have the same uncertainty in the i2c bus acquisition, but the old device driver "hides" this irregularity in the way it takes the timestamp.

Closing.
