### ISSUE TITLE
Cannot find how to enable Python bindings

### ISSUE THREAD

**Issue by Urheen** [robotology/icub-main#602]
I installed iCUb via the command sudo apt-get install icub.
Then when I try to install python binding, I can not find the main folder under the iCub. My iCub version is 1.12, and under the directory it only has:

cmake  contexts  modules  plugins  templates

Could you help me how to install python binding under this case?

**Comment by pattacini** [comment]
Hi @Urheen 

Bindings are only available through the source. Therefore, you ought to clone the repository and build `icub-main` yourself. At cmake time, you should find the option to enable python bindings.
