### ISSUE TITLE
Remove GTK2-based modules

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#606]
This issue is part of #193 .

**Comment by traversaro** [comment]
@pattacini mentioned that it could be a good idea to move the code (even in a state that is not compiling) in https://github.com/robotology-legacy .

**Comment by traversaro** [comment]
As a preliminary step, we explicitly set `ICUB_USE_GTK2` to `OFF` in the robotology-superbuild in https://github.com/robotology/robotology-superbuild/pull/266 .

**Comment by Nicogene** [comment]
> @pattacini mentioned that it could be a good idea to move the code (even in a state that is not compiling) in https://github.com/robotology-legacy .

I agree

**Comment by pattacini** [comment]
For porting the code, a simple fork in the dedicated legacy org should be sufficient.

**Comment by pattacini** [comment]
Done in #659 by @Nicogene ✨
