### ISSUE TITLE
merge together camCalib, dualCamCalib, camCalibWithPose

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#607]
This issue is part of #193 .

**Comment by Nicogene** [comment]
We should also consider to include in this refactoring also `camCalibWithPose`

**Comment by drdanz** [comment]
just for reference, `camCalibWithPose` is an ugly hack and should be re-architectured

**Comment by drdanz** [comment]
I wrote it, therefore I'm allowed to be disgusted 😉

**Comment by alecive** [comment]
Well that changes things a bit :-) 
I was already picturing a poor phd student crying in a corner because you didn't like his code 🤣

**Comment by pattacini** [comment]
This won't happen any time in the future.

**Comment by alecive** [comment]
![image](https://github.com/robotology/icub-main/assets/4378663/49b81829-9055-4d9f-a8dd-168b56e8702c)
