### ISSUE TITLE
camCalibWithPose crashes on Windows

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-main#611]
I am trying to use `camCalibWithPose`  on a Windows machine and I have the following problems:
1.  When I tried to connect the ports (`\icub\head\state:o` and the `icub\cam\left`) the program crashed. We (@kouroshD) compiled the code in `RelWithDebugInfo` and we discovered that it crashed at the following line https://github.com/robotology/icub-main/blob/0a2e1d909fd1466565b2bcab4f755d59e61f7451/src/modules/camCalibWithPose/src/CamCalibModule.cpp#L110
   With the following error 
    ```
    Unhandled exception thrown: read access violation. pixel was 0x181FCEE3000
    ```
    ![camcalib](https://user-images.githubusercontent.com/16744101/66390886-f33ced00-e9cb-11e9-911c-cfff4261bc4d.png)

2. camCalibWithPose sometimes does not crashes but `icub/camcalib/left/out/` is always empty

Do you have any idea? @drdanz @S-Dafarra @kouroshD @randaz81

**Comment by pattacini** [comment]
@Nicogene [this commit][1] removed from the triplet {`camCalib`, `camCalibWithPose`, `dualCamCalib`} the memory allocation of the image `out`. Can this be potentially causing the crash as the following call comes right before the line @GiulioRomualdi has spotted?
https://github.com/robotology/icub-main/blob/0a2e1d909fd1466565b2bcab4f755d59e61f7451/src/modules/camCalibWithPose/src/CamCalibModule.cpp#L105

Don't know why `camCalib` seems to be working though...

[1]: https://github.com/robotology/icub-main/commit/7a235125cf9d188270c29ce32cdc6e200d813276#diff-15887b0326c3d2d40911667ef7299ea4

**Comment by Nicogene** [comment]
Actually all the camera calibration software have problems since a while (e.g. https://github.com/robotology/icub-main/issues/478). 
This segfault on windows happens systematically?
I used `camCalibWithPose` with @drdanz for the oculus and it worked on windows but I don't know honestly if it was the last version of `icub-main`.

**Comment by Nicogene** [comment]
Another question

>When I tried to connect the ports (\icub\head\state:o and the icub\cam\left) the program crashed. We (@kouroshD) compiled the code in RelWithDebugInfo and we discovered that it crashed at the following line

I don't know how `camCalibWIthPose` specifically works, but why are you connecting the state of the head and the port of the camera??

**Comment by traversaro** [comment]
If you need to debug memory problems on Windows, Dr. Memory is a great tool even if the homepage is really '90 ( https://drmemory.org/ ).

**Comment by Nicogene** [comment]
Chatting with @GiulioRomualdi it emerged that it happens systematically and that it happens **only** on windows. On Linux it works fine.

**Comment by pattacini** [comment]
Hi @GiulioRomualdi 

In the end, we judged that `camCalibWithPose` needs a deep refactoring, thus we haven't planned any debug activity to devote to this, in its present version.

For the task of refactoring, @Nicogene has opened up a dedicated issue on our internal workflow (https://github.com/icub-tech-iit/fix/issues/133).
