### ISSUE TITLE
skinGui should not show temperature pads by default

### ISSUE THREAD

**Issue by lornat75** [robotology/icub-main#62]
It has been reported that by default the skinGui shows temperature pads. This is sometimes misleading for users bc it is difficult to tell the difference between temperature pads and actual pads. On the other hand temperature pads should be displayed only for debug and their output is used internally for compensation. 

Default for the gui should be to not display temperature pads.It should be an easy fix.

@ale-git, can you implement this? @alecive given that you will be checking the development of the new skingui based on qt I recommen you follow closely this development.

**Comment by pattacini** [comment]
@ale-git could we look into this?
