### ISSUE TITLE
Remove skinprototype device

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#632]
The device has been not used for a long time and has been superseded by [`canBusSkin`](https://github.com/robotology/icub-main/tree/master/src/libraries/icubmod/canBusSkin), and all its use in the robots-configuration repo is in file for the old iCubInterface, that has been removed from the repo several years ago (see https://github.com/robotology/robots-configuration/search?p=2&q=skinprototype&type=&utf8=%E2%9C%93). For this reason, I think it can be safely removed.

**Comment by traversaro** [comment]
This will avoid problems such as https://github.com/robotology/icub-main/issues/631 .

**Comment by pattacini** [comment]
Done in #633.
