### ISSUE TITLE
Latest iCubSheffield01 compatible distro

### ISSUE THREAD

**Issue by dcam0050** [robotology/icub-main#638]
https://github.com/robotology/icub-main/issues/631#issuecomment-567082326

Please advise on the latest distro compatible with iCubsheffield01

**Comment by pattacini** [comment]
Hi @dcam0050 
Could you please provide us with the current tags of the software installed on your system?

The relevant software components can be browsed at http://wiki.icub.org/wiki/Software_Versioning_Table.

**Comment by dcam0050** [comment]
For the latest update I have been updating all the release tags to 1.14 for iCub related repos and 3.3 for yarp as mentioned on the link. I will check that I have also updated iCub-firmware. I'm sure I've updated iCub-firmware-build and iCub-firmware-shared to 1.14

**Comment by dcam0050** [comment]
I can also provide the tags from a backup of the previous installation once I get into the lab

**Comment by pattacini** [comment]
Hi @dcam0050 

I'm afraid that `iCubSheffield01` is not eligible for the upgrade to the tags you reported as we clearly stated in https://github.com/robotology/QA/issues/377.

Is there any particular reason why you proceeded with the update anyway?

**Comment by pattacini** [comment]
I've also warned you not to do the upgrade on the robot system: see https://github.com/robotology/icub-main/issues/631#issuecomment-567082326.

**Comment by pattacini** [comment]
My recommendation is to go back to the old tags you wisely took a backup of and await our next distro 2020.02, which is expected to be provided next month and will cope with `iCubSheffield01`.

How do you see that?

**Comment by pattacini** [comment]
Closing, feel free to open it up again if needed.

**Comment by dcam0050** [comment]
Thanks @pattacini We will wait for 2020.02 before updating any sources.
