### ISSUE TITLE
Install relocatable CMake config files

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#651]
As of version v1.15.1 , the `ICUB` CMake package install CMake config files that contains absolute references to the `CMAKE_INSTALL_PREFIX` of the machine in which they were generated, making the installation artifacts non-relocatable (see https://cmake.org/cmake/help/v3.3/manual/cmake-packages.7.html#creating-relocatable-packages). 

This is problematic for two reasons:
* Windows binary installers (the current workaround is to force the installation to be in the same exact directory used for the install in the build machine) 
* Cache for CI (see https://github.com/robotology/whole-body-estimators/issues/60) 

It would be ideal if icub-main could install relocatable CMake config files. A possible strategy is to use YCM's `InstallBasicPackageFiles` as we do in https://github.com/robotology/how-to-export-cpp-library, removing the old hard coded logic for generating the CMake config  files contained in this repo.

**Comment by pattacini** [comment]
This would be a nice improvement indeed.
Is anyone eager to take on it?

I'm not sure I'll have time for it.
cc @Nicogene @traversaro

**Comment by traversaro** [comment]
I may work on it in the next months, but I do not have a precise schedule yet. Obviously if there are other volunteers that would be great.

**Comment by Nicogene** [comment]
I may handle it, but since icub-main is slightly more articulated than repos i worked on (cmake-side) i would need support

**Comment by traversaro** [comment]
I would be happy to provide support.

**Comment by Nicogene** [comment]
Fixed by #652
