### ISSUE TITLE
Controlling the RFE Eyelids - Tested

### ISSUE THREAD

**Issue by dariopasquali** [robotology/icub-main#669]
Hi @Nicogene ,
Sorry for the double issue, but I can't reopen #665 

I tested both the `emotionInterface` and `ICubBlinker` modules on iCubGenova07 cloning from `devel` branch.
**Both the modules failed**. The main issue is they are totally unreliable.

However, after a few tests, I strongly think that this is not related to the control but it is a design issue. The motor that moves the eyelids is not supposed to control such a quick-moving component.

### emotionInterface
I noticed how you tried to avoid hitting the bottom limit by balancing the moving range and the moving speed.
However, you configuration does not work on our robot.
I tuned the min-max eyelids boundaries and the blinking speed.

The maximum speed that does not it the limit putting the eyelids in `HW_FAULT` is **40**.
However, this is not reliably since sometimes it works and sometime it hits the limit.

Decreasing the speed generates a too slow movement.

### iCubBlinker
They are slower as you said, but the have the same issue of the `emotionInterface`. Sometimes they work, sometimes they fail

So, do you think is possible to redesign the eyelids motor control?

## Eyelids positions as percentage

I would propose you to change from a `00p -> 10p` encoding to a `00p -> 99p` encoding.
Right now you basically give the possibility to set 10 fixed positions out of 100. 
This way we can have a more precise control and you don't have to change the .ini file parsing. just move from a `stod` to a `stoi` percentage evaluation.

Also, the `emotion_rfe.ini` file is still wrong
```ini
E1   neu 00h 00h 00h 00p
E2   ta1 **h **h 00h **p
E3   ta2 **h **h 03h **p
E4   hap 01h 01h 01h 10p
E5   sad 02h 02h 02h 00p
E6   sur 03h 03h 03h 00p
E7   ang 04h 04h 04h 10p
E8   evi 05h 05h 05h 10p
E9   shy 06h 06h 06h 10p
E10  cun 07h 07h 07h 00p
```
`neu`, `sad`, `sur` and `cun` have completely closed eyes

**Comment by pattacini** [comment]
Hi @dariopasquali 

It's not a mere software problem, unfortunately.
As you've been experiencing yourself, we've also noticed that the HW per se is unreliable in certain aspects, in particular relating to the speed of the movements and the occurrence of faults. Software-wise, we can't easily circumvent or patch these unwanted behaviors.

Therefore, we've just filed a ticket on our internal system for managing the activities required by this mechanical overhaul.
Interestingly enough, we're in touch with Diego Torazza at Erzelly who designed a solution that can be very useful to get around these current downsides.

That said, this is not the right place to discuss this issue any further. To any rate, Your PI/Head should have access to our ticketing system and let you get updated on this. Our plan is to produce an upgrade kit to be delivered likely in the next program increment.
