### ISSUE TITLE
icub-main fails to compile on Windows 10 using Visual Studio 16 2019

### ISSUE THREAD

**Issue by S-Dafarra** [robotology/icub-main#678]
I tried to install it on a clean Windows 10 installation using Visual Studio 16 2019
Here the errors:
```sh
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	joystickCheck	C:\robotology-superbuild\build\robotology\ICUB\src\tools\joystickCheck\MSVCRTD.lib(exe_main.obj)	1	
Error	LNK1120	1 unresolved externals	joystickCheck	C:\robotology-superbuild\build\robotology\ICUB\bin\Debug\joystickCheck.exe	1	
Error	LNK2019	unresolved external symbol main referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)	joystickCtrl	C:\robotology-superbuild\build\robotology\ICUB\src\tools\joystickCtrl\MSVCRTD.lib(exe_main.obj)	1	
Error	LNK1120	1 unresolved externals	joystickCtrl	C:\robotology-superbuild\build\robotology\ICUB\bin\Debug\joystickCtrl.exe	1	
Error	LNK2019	unresolved external symbol MAIN__ referenced in function main	iCub_SIM	C:\robotology-superbuild\build\robotology\ICUB\src\simulators\iCubSimulation\libifcoremdd.lib(for_main.obj)	1	
Error	LNK1120	1 unresolved externals	iCub_SIM	C:\robotology-superbuild\build\robotology\ICUB\bin\Debug\iCub_SIM.exe	1	
```

Here's attached the complete build log:

[buildlog.txt](https://github.com/robotology/icub-main/files/5150125/buildlog.txt)

Any hint? @Nicogene @traversaro @prashanthr05

**Comment by traversaro** [comment]
I remember having a similar issue in https://github.com/robotology/robotology-superbuild/issues/128#issuecomment-433695438 . Can you paste the `CMakeCache.txt` of `ICUB`?

**Comment by S-Dafarra** [comment]
It's a 1528 lines long file. So I rather attach it as a file.
Here it is! [CMakeCache.txt](https://github.com/robotology/icub-main/files/5150276/CMakeCache.txt)

**Comment by traversaro** [comment]
> 
> 
> It's a 1528 lines long file. So I rather attach it as a file.
> Here it is! [CMakeCache.txt](https://github.com/robotology/icub-main/files/5150276/CMakeCache.txt)

The found SDL seems to be indeed the vcpkg one, that is working fine in CI (see https://github.com/robotology/robotology-superbuild/runs/1049179020). If you don't need those tools you can simply set `ICUB_USE_SDL` to `FALSE` . Otherwise, we need to understand what is going on. I guess there is some SDL library that is providing the `main` symbol, and for some reason it is not linked.

**Comment by S-Dafarra** [comment]
After setting ``ICUB_USE_SDL`` to ``FALSE``, it compiles successfully.

**Comment by S-Dafarra** [comment]
This was probably due to a mistake of mine in dealing with the dependencies as I did not follow the [README](https://github.com/robotology/robotology-superbuild-dependencies-vcpkg#install-or-remove-vcpkg-ports) correctly. By reinstalling the dependencies and the ``robotology-superbuild`` I don't have this issue anymore.
