### ISSUE TITLE
[coman] Impedance Ctrl at DSP level

### ISSUE THREAD

**Issue by EnricoMingo** [robotology/icub-main#7]
When switching to Impedance/Torque Ctrl the firmware expects a torque reference every x ms so we need to assure that reference, if not the board goes in protection. This issue is to remeber to check this with Alessio M.

**Comment by pattacini** [comment]
@EnricoMingo did you check this with @arocchi ?

**Comment by iron76** [comment]
Sorry, I was referring to robotology/icub-support#7
