### ISSUE TITLE
ssgprtune script in the learningMachine module is outdated

### ISSUE THREAD

**Issue by agijsberts** [robotology/icub-main#721]
Hi all,

The `learningMachine` module comes with a `ssgprtune` script written in Python to pretrain optimized incremental sparse spectrum GPR models for deployment via the module. Unfortunately, the code is in Python 2 and makes use of OpenOpt, which is no longer being maintained.

Since I occasionally still receive requests for the incremental SSGPR code, not long ago I have split off these scripts and cleaned them up: Python 3, removed OpenOpt, `setup.py` and some tests and documentation. The result is available on https://github.com/agijsberts/ssgpr.

May I propose to replace the outdated version in the `icub` repository with a pointer to the dedicated `ssgpr` repository (e.g., via a simple textfile or perhaps a git submodule)?

**Comment by pattacini** [comment]
Hi Arjan, good to hear from you again!
Sure, go ahead with your proposal and open up a pull request.
No git submodule, please! A markdown file filled with some documentation and proper pointers should be spot on!

**Comment by traversaro** [comment]
fyi @singhbal-baljinder @raffaello-camoriano

**Comment by pattacini** [comment]
Done in #722 ✔
