### ISSUE TITLE
staticgrabber could be removed

### ISSUE THREAD

**Issue by drdanz** [robotology/icub-main#748]
### Bug description

The `staticgrabber` device opens a `.ppm` files, and publishes its content on a port as Image.
This is supported also by the `fakeFrameGrabber` in YARP, therefore there is no reason to have the same functionality in 2 places.

### Steps to reproduce

N/A

**Comment by pattacini** [comment]
Hi @drdanz 

Thanks for reporting. Sorry, but I completely missed this from my GH dashboard (likely, I wast too fast while scrolling the issues).

I'll do that.

**Comment by pattacini** [comment]
Fixed via #774.
