### ISSUE TITLE
macOS iCub_SIM not executing

### ISSUE THREAD

**Issue by smwasif** [robotology/icub-main#777]
Hi dear,
I am new bee to macOS and i installed from robotology-superbuild using source installation by following step by step guide provided at this page. Installation was successful without any error in both conda and without conda installation. In both cases `**yarpserver** `started but whenever i executed `**iCub_SIM**` command I got this result:
**command not found: iCub_SIM**
Please help to address this issue or appropriate command to start `**iCub_SIM**`  in macOS.

**Comment by smwasif** [comment]
Hi @traversaro 
Thank you very much for updating me regarding iCub_SIM legacy simulator. Actually, in past I used the legacy simulator in Ubuntu environment. Now i need help  for Gazebo-based iCub simulator usage in macOS.

**Comment by traversaro** [comment]
> Now i need help for Gazebo-based iCub simulator usage in macOS.

Which kind of help do you need in particular? Once you installed the robotology-superbuild with `ROBOTOLOGY_USES_GAZEBO`, if you start `yarpserver` and then `gazebo`, you can see the iCub-related model of Gazebo on the left panel.

**Comment by smwasif** [comment]
Hi @traversaro 
How to install ROS in macOS? more precisely whether should I install ros2 or version 1 ? There are number of pages available instructing its installation e.g., [https://docs.ros.org/en/foxy/Installation/macOS-Development-Setup.html](url). 
If you could please guide me specifically for ROS installation steps in macOS Monterey followed by gazebo based iCub simulator.

**Comment by traversaro** [comment]
Hi @smwasif,
  ROS is not required to run the iCub on Gazebo simulation. I am not sure how are you installing your dependencies, but you can install gazebo on conda with:
~~~
conda install -c conda-forge gazebo
~~~
or with homebrew with:
~~~
brew install gazebo
~~~

**Comment by traversaro** [comment]
Hi @smwasif, do  you still have problems or we can close this issue? Thanks!

**Comment by pattacini** [comment]
Closing.
Feel free to open it up again if needed.
