### ISSUE TITLE
Magnetometer streams zero when embObjIMU and multipleanalogsensorsserver is used 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-main#824]
### Bug description

We are trying to stream the data of the magnetometer on iCubGenova09. We noticed that the data are constantly equal to zero. 

This is an example of the device we run on the robot
https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova09/iCubGenova09/hardware/inertials/left_arm-eb1-IMU.xml
and this is the associated network wrapper https://github.com/ami-iit/robots-configuration/blob/devel_iCubGenova09/iCubGenova09/wrappers/inertials/left_arm-IMU_wrapper.xml

### Steps to reproduce

Run the robot yarprobotinterface and read one of the IMUs for instance `/icub/left_arm/imu/measures:o` with 

```
yarp read ... /icub/left_arm/imu/measures:o
```

This is the output
```
(((-0.125 0.0625 0.0) 1663162136.8404417038)) (((-5.3099999999999996092 -4.11000000000000031974 -6.91000000000000014211) 1663162136.84044075012)) (((0.0 0.0 0.0) 1663162136.84044098854)) (((-149.1875 32.875 234.75) 1663162136.84044194221)) () () () () () ()
```

### Additional context

cc @pattacini @triccyx @S-Dafarra @isorrentino

**Comment by pattacini** [comment]
Closing this in favor of the more recent task:
- https://github.com/robotology/icub-tech-support/issues/1485
