### ISSUE TITLE
iCubGUI won't start

### ISSUE THREAD

**Issue by serena-ivaldi** [robotology/icub-main#84]
Hi, I'm trying to launch iCubGui but it gives the following error and simply doesn't start:

<..>
||| found /home/icub/software/share/iCub/contexts/iCubGui/icons/play.png
Object::connect: No such signal Q3Action::triggered()
Object::connect:  (sender name:   'playAction')
Object::connect:  (receiver name: 'MainWindow')
iCubGui: symbol lookup error: iCubGui: undefined symbol: _ZN4yarp2os6Bottle4findERKNS0_11ConstStringE

any idea?

**Comment by lornat75** [comment]
Looks like a linking problem from mixed compilation... sorry to say the obvious but are you sure you have only one version of yarp+icub in the system and that you are not mixing different versions of yarp header files and compiled libraries?
