### ISSUE TITLE
Deal with modules still relying on `FrameGrabberInterfaces.h`

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-main#864]
### Bug description

The I/F `yarp/dev/FrameGrabberInterfaces.h` has been declared deprecated since `YARP-3.5.0`.
However, we do still have a few modules depending on it:
- `frameGrabberGui2`
- `dragonfly2`

### Steps to reproduce

See https://github.com/search?q=repo%3Arobotology%2Ficub-main%20FrameGrabberInterfaces&type=code.

**Comment by pattacini** [comment]
cc @Nicogene

**Comment by pattacini** [comment]
See also https://github.com/orgs/robotology/discussions/621#discussioncomment-5940831.

**Comment by Nicogene** [comment]
The only device that still relies on deprecated interfaces is `dragonfly2`, but the methods of those interfaces are not used since a while.

see #882 

> See also [github.com/orgs/robotology/discussions/621#discussioncomment-5940831](https://github.com/orgs/robotology/discussions/621#discussioncomment-5940831).

I am afraid this is related to something else.
