### ISSUE TITLE
Update icub-main modules to the use of MAS for MAIS boards

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-main#908]
### The solution you would like to have available

Following-up of #851, right now the MAIS are published via `multipleanalogsensorsserver`, then we need to adapt the code in order to not use anymore the `analog:o` port but the `multipleanalogsensorsclient`.

**Comment by pattacini** [comment]
I'll deal with the module `depth2kin`, @davidetome.
If there's something else to address, we will coordinate.

**Comment by pattacini** [comment]
PR opened:
- https://github.com/robotology/icub-main/issues/908

**Comment by pattacini** [comment]
There shouldn't be any other component requiring update.
