### ISSUE TITLE
Can we do a 2.4.1 release of icub-main?

### ISSUE THREAD

**Issue by traversaro** [robotology/icub-main#926]
### Is your feature request related to a problem?

In https://github.com/robotology/robotology-superbuild/pull/1548#issuecomment-1862920609 it would be convenient to have a 2.4.1 release of icub-main that is compatible with YARP 3.9.0 

### The solution you would like to have available

Do the release.

### Alternatives you have considered

Don't do the release.

### Additional context

https://github.com/robotology/robotology-superbuild/pull/1548

**Comment by pattacini** [comment]
Hi @traversaro 

Done!
Here it is:
- https://github.com/robotology/icub-main/releases/tag/v2.4.1
