### ISSUE TITLE
Wrong `bodyPartId` is assigned to skin on legs in `skinContactList` on `/skinManager/skin_events:o`

### ISSUE THREAD

**Issue by rustlluk** [robotology/icub-main#933]
### Bug description

When reading data through `skinManager` on `/skinManager/skin_events:o` ([Reading High Level Contact Data
](https://icub-tech-iit.github.io/documentation/tactile_sensors/software/reading_data/#reading-high-level-contact-data)), skin on legs (LEFT/RIGHT_LEG_UPPER, LEFT/RIGHT_LEG_LOWER, LEFT/RIGHT_FOOT) get correct skinPart assigned with respect to [skinPart enum in skinDynLib/common.h](https://github.com/robotology/icub-main/blob/92430ce9c1a249964f99382da3df7a91537fd42e/src/libraries/skinDynLib/include/iCub/skinDynLib/common.h#L56-L63C3), but bodyPartId is always 0 (BODY_PART_UNKNOWN). 

### Steps to reproduce

Run skinManager with any config that contains skin on legs and read data on /skinManager/skin_events:o

### Expected behavior

The correct `bodyPartId` for skin on left leg should be 5 (`LEFT_LEG`), and 6 (`RIGHT_LEG`) for the right leg. From [BodyPart enum](https://github.com/robotology/icub-main/blob/92430ce9c1a249964f99382da3df7a91537fd42e/src/libraries/skinDynLib/include/iCub/skinDynLib/common.h#L44-L48).

### Additional context

The error is probably coming from not having the association of skin on legs to body part in [SkinPart_2_BodyPart in skinDynLib/common.h](https://github.com/robotology/icub-main/blob/92430ce9c1a249964f99382da3df7a91537fd42e/src/libraries/skinDynLib/include/iCub/skinDynLib/common.h#L77-L87) and thus function [iCub::skinDynLib::getBodyPart(SkinPart s)](https://github.com/robotology/icub-main/blob/92430ce9c1a249964f99382da3df7a91537fd42e/src/libraries/skinDynLib/src/common.cpp#L26-L32) returns `BODY_PART_UNKNOWN`.  But I am not brave enough to compile and test the library on our robot :)

**Comment by pattacini** [comment]
Thanks @rustlluk for reporting 👍🏻 
We will probably deal with this while checking #932.

**Comment by traversaro** [comment]
@rustlluk do you actually are using bodyPartId somewhere? That part of the code is quite iCub-centric, and it would be great to make it more general. However, to do so we would need to understand how people are actually using data like bodyPartId .

**Comment by rustlluk** [comment]
Well, actually not.  I would say that `bodyPartId` and `linkNumber` are redundant, as you can easily extract both from `skinPart`.  @traversaro 

I even looked to an old code I used with our Nao with skin and the only thing I did with `bodyPartId` was saving it to log.

**Comment by Nicogene** [comment]
Unfortunately the iCub we have here have not the legs, but I can backtrack the code that assigns the bodypart and try to fix it, the other parts are ok instead.
