### ISSUE TITLE
FirmwareUpdater - ERROR message on successful FW flashing.

### ISSUE THREAD

**Issue by davidetome** [robotology/icub-main#939]
### Bug description

When you do Upload Application, the message in the terminal at the end of the programming returns a failed operation even if it went well.

```bash
EthMaintainer::cmdProgram() is about to program the APP partition of 1 boards: 10.0.1.1 (candoit)
ERROR: EthMaintainer::program() could not program board none @ 0.0.0.0: 10.0.1.1: APP NOK
```

### Steps to reproduce

- Open Firmware Updater
- Do a discover
- Select an ETH board, an `mc4plus` (in my case) 
- Put the board un Maintenance
- Do Upload Application
- See the FAIL message in the terminal

### Expected behavior

The message should report a successful operation (APP OK)

**Comment by davidetome** [comment]
cc @valegagge

**Comment by davidetome** [comment]
I found the reason of the failure, in the `command_program` method because [two indexes differ by one](https://github.com/davidetome/icub-main/blob/686cfdac1b9bb8ac76e253e0d62808e41225a8a9/src/tools/ethLoader/ethLoaderLib/EthMaintainer.cpp#L566) 

I also noticed that one of them is increased by one just after [it is initialized at zero](https://github.com/davidetome/icub-main/blob/686cfdac1b9bb8ac76e253e0d62808e41225a8a9/src/tools/ethLoader/ethLoaderLib/EthMaintainer.cpp#L337)

Commenting out it, the program operation works properly : 

![image](https://github.com/robotology/icub-main/assets/6638215/c97121c1-d8d1-4ca2-b7ef-ec43c80a6914)

I have to double-check if it is ok to comment out this [line](https://github.com/davidetome/icub-main/blob/686cfdac1b9bb8ac76e253e0d62808e41225a8a9/src/tools/ethLoader/ethLoaderLib/EthMaintainer.cpp#L337) 👍🏼 

cc @valegagge

**Comment by davidetome** [comment]
I tested the mod w/ 2 mc4plus and one ems and it works properly 👍🏼 

### 2 mc4plus programmed in parallel successfully
![1](https://github.com/robotology/icub-main/assets/6638215/1503a6c8-b2cd-47bf-be28-e7002c9a935c)

### 1 ems programmed successfully
![2](https://github.com/robotology/icub-main/assets/6638215/39a0e5e6-089b-4f6c-a6c6-ecaa970eb9bc)

Now I'm going to fix the message : 

```
OK: EthMaintainer::program() has succesfully programmed board none @ 0.0.0.0.
```
cc @valegagge

**Comment by davidetome** [comment]
## Fixed message
With this [commit](https://github.com/robotology/icub-main/compare/devel...davidetome:icub-main:devel) in my fork I fixed also the message in the terminal : 

### 2 mc4plus programmed in parallel successfully
![1](https://github.com/robotology/icub-main/assets/6638215/dd2f88de-539f-4e2b-82d7-255ded656364)

### 1 ems programmed successfully
![2](https://github.com/robotology/icub-main/assets/6638215/c72641af-3b9a-4699-a13f-7888ebe8b963)

@valegagge I wait for your green light 🚦 to rebase and open the PR 👍🏼

**Comment by pattacini** [comment]
Hi @davidetome 

The issue will be closed upon merging the PR.
