### ISSUE TITLE
Add a tool to read the motor temperature

### ISSUE THREAD

**Issue by valegagge** [robotology/icub-main#940]
### Is your feature request related to a problem?

Currently, the motor temperature is not published on the `stateExt` port. 

### The solution you would like to have available

We need an application that reads the temperatures of a part or a subset of a part and publishes it on a port to plot with `yarpscope`

**Comment by valegagge** [comment]
Just some tips:
 - the [motionControlModule](https://github.com/MSECode/motionControlModule) can be added in src/tools
 - its configuration files can be inserted in `app` folder and collected in a new folder with the name of the module. Please follow the camel case convention.

**Comment by pattacini** [comment]
>- add the [motionControlModule](https://github.com/MSECode/motionControlModule) in icub-main/src/tools

I would only find a better self-explaining name 😄

Just a couple of examples to give you an idea:
- `mootorTemperatureDumper`
- `motorTemperaturePublisher`

**Comment by valegagge** [comment]
Hi @pattacini,
thank you for all the tips!

I know the `control board dumper`. It publishes the temperatures also, but it calls the `getTepersature**s**` API that in case of an error in one of a sensor it returns false for all the sensors.

So I prefer to use the API for single joint. Anyway, we can consider changing it with the call to the API for single joint, but, if I'm not mistaken, it is hard to change for its general-purpose design. I still need to check the code... 

Concerning the name, for sure we need to use one more significant... 😸

**Comment by pattacini** [comment]
Development integrated in `devel` via:
- https://github.com/robotology/icub-main/pull/951

Closing.
Feel free to open it up again if required.

**Comment by pattacini** [comment]
Here's the related online documentation:
- https://robotology.github.io/robotology-documentation/doc/html/group__MotorTemperaturePublisher.html
