### ISSUE TITLE
ICub + Gazebo + joint states on ROS1

### ISSUE THREAD

**Issue by omareldardear** [robotology/icub-main#994]
### Bug description

I am trying to have the joint states  (iCub Gazebo)published on ROS and visualizing it on Rviz Following what is mentioned in the documentation 
-> https://icub-tech-iit.github.io/documentation/icub_ros/#what-is-ros-tf 
and the README on icub-models 
-> https://github.com/robotology/icub-models/blob/master/iCub_manual/ros/README.md

I am not really familiar with the process, so I am not sure if I missing something or if there is a bug. 
I have added the wrapper line in the configuration file of yarprobotinterface (no_legs.xml) 
 <xi:include href="wrappers/motorControl/icub_ros_wrapper.xml" />

no topics appeared on ROS

Thanks in advance. 

### Steps to reproduce

OS: Ubuntu 20.04
ROS1 Noetic 
Superbuild: v2024.08.0
Gazebo 11
Using the following process

ROS_MASTER_URI set correctly on bashrc 
* $roscore
* $yarpserver --ros
* $gazebo 
* Placing iCub Model -> iCubGazeboV2_5 (no_hands)
* $yarprobotinterface --context gazeboCartesianControl --config no_legs.xml

$rostopic echo 

no topics for iCubSim here 

### Additional context

no_legs.xml 

<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE robot PUBLIC "-//YARP//DTD yarprobotinterface 3.0//EN" "http://www.yarp.it/DTD/yarprobotinterfaceV3.0.dtd">
<robot name="icubSim" portprefix="icubSim" build="0" xlmns:xi="http://www.w3.org/2001/XInclude">

    <device name="torso" type="remote_controlboard">
        <param name="remote"> /icubSim/torso </param>
        <param name="local"> /gazeboCartesianControl/torso </param>
        <param name="writeStrict"> on </param>
    </device>

    <device name="left_arm" type="remote_controlboard">
        <param name="remote"> /icubSim/left_arm </param>
        <param name="local"> /gazeboCartesianControl/left_arm </param>
        <param name="writeStrict"> on </param>
    </device>

    <device name="right_arm" type="remote_controlboard">
        <param name="remote"> /icubSim/right_arm </param>
        <param name="local"> /gazeboCartesianControl/right_arm </param>
        <param name="writeStrict"> on </param>
    </device>

    <xi:include href="./cartesian/left_arm_cartesian.xml" />
    <xi:include href="./cartesian/right_arm_cartesian.xml" />
    
    
     
    <xi:include href="wrappers/motorControl/icub_ros_wrapper.xml" />
    
</robot>

**Comment by pattacini** [comment]
Hi @omareldardear 

Great that you aim to use ROS on iCub.

Since our official documentation is a bit outdated in this respect[^1], would you mind filing an issue at https://github.com/icub-tech-iit/xcub-moveit2 instead?

Thanks heaps!

[^1]: @Nicogene @martinaxgloria we should reserve some effort to address this.

**Comment by omareldardear** [comment]
Sure, 
I am trying with ROS1 though

**Comment by pattacini** [comment]
Hi @omareldardear 

Did you consider moving to ROS2?

ROS1[^1] is something that we don't really support any longer, also given the work we did in https://github.com/icub-tech-iit/xcub-moveit2. I know, the warning highlighted in https://icub-tech-iit.github.io/documentation/icub_ros/ is misleading and we definitely need to fix it.

[^1]: ROS1 is also close to EOL, which is around May 2025.

**Comment by omareldardear** [comment]
Yes. 
I am actually more familiar with ROS2. 
At the moment, I am trying to integrate iCub with other existing software on ROS1 (the ROS2 version is under development) . 
I am happy to actually adopt ROS2 and use the ros_bridge. 

I wasn't aware of movit repository until you just mentioned it. 
I will try to follow the README there and see If I can manage. 
If you have any other suggestions let me know. 
Thanks

**Comment by omareldardear** [comment]
I will close this issue then and will follow up on the copied issue on xcub-moveit2 repo 
https://github.com/icub-tech-iit/xcub-moveit2/issues/26

**Comment by pattacini** [comment]
Great!
